$axure.loadCurrentPage({
  "url":"签到.html",
  "generationDate":new Date(1438070190514.96),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"86d7205f2f86447cbcfa46a364e6a99a",
    "type":"Axure:Page",
    "name":"签到",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"5ae154e2bfb147889c163f746441d7f1",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"0b7481d9291846af9389708a818f6ee6"},
{
          "id":"19af92c1bce942cfab26abcbe68a41f4",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":36,
              "y":109},
            "size":{
              "width":320,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"000616cdd8ab44ef9fc69aa09ea6a863",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":36,
                  "y":109},
                "size":{
                  "width":320,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注册/u23.png"}},
{
          "id":"1d5f27f3520548a3b0ef938c3532057b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":47,
              "y":120},
            "size":{
              "width":18,
              "height":18},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8160509f98c744d095abf2b648fda92b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":47,
                  "y":120},
                "size":{
                  "width":18,
                  "height":18},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 优惠券",
                      "target":{
                        "targetType":"page",
                        "url":"优惠券.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/注册/u25.png"}},
{
          "id":"1ab4f992ca694fdc9dbe9d975f959b85",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF333333},
            "location":{
              "x":211,
              "y":515},
            "size":{
              "width":130,
              "height":40},
            "cornerRadiusTopLeft":"3"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4653fd15eb624d4aba317287cc6644fb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF333333},
                "location":{
                  "x":211,
                  "y":515},
                "size":{
                  "width":130,
                  "height":40},
                "cornerRadiusTopLeft":"3"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 登录",
                      "target":{
                        "targetType":"page",
                        "url":"登录.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/签到/u27.png"}},
{
          "id":"156ce192fc1d48e681b7492786357600",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"14px",
            "fontWeight":"700",
            "location":{
              "x":50,
              "y":526},
            "size":{
              "width":115,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"af9427778fbb4e339a02db2a1e2b4cea",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"14px",
                "fontWeight":"700",
                "location":{
                  "x":50,
                  "y":526},
                "size":{
                  "width":115,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0cf06ef0da944752b35e869e4f6ac7d2",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":50,
              "y":158}},
          "adaptiveStyles":{
},
          "masterId":"f85a4329c07a4f10882ec32eccff2b14"},
{
          "id":"15eee5174e4a47c48f6833f80d9ebdb7",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":150,
              "y":158}},
          "adaptiveStyles":{
},
          "masterId":"f85a4329c07a4f10882ec32eccff2b14"},
{
          "id":"67393dcfc1144f2397e7c9cf36a47f05",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":250,
              "y":158}},
          "adaptiveStyles":{
},
          "masterId":"f85a4329c07a4f10882ec32eccff2b14"},
{
          "id":"0953079bca41407987efd8eca4aedfa7",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":50,
              "y":298}},
          "adaptiveStyles":{
},
          "masterId":"f85a4329c07a4f10882ec32eccff2b14"},
{
          "id":"882aba52073741bb9973cf0daf2d44fb",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":150,
              "y":298}},
          "adaptiveStyles":{
},
          "masterId":"f85a4329c07a4f10882ec32eccff2b14"},
{
          "id":"bc1a276a736c4c5b8a3faf7a6e3b1207",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":250,
              "y":298}},
          "adaptiveStyles":{
},
          "masterId":"f85a4329c07a4f10882ec32eccff2b14"},
{
          "id":"92e11fca761e47bcb69a696634203c06",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":35,
              "y":469},
            "size":{
              "width":320,
              "height":33},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e4db0ee050494b8499b2e7cc793e8e53",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":35,
                  "y":469},
                "size":{
                  "width":320,
                  "height":33},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/签到/u73.png"}},
{
          "id":"c77e01020057420784f8e8764f806fbe",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":35,
              "y":437},
            "size":{
              "width":320,
              "height":33},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2e402407502b4bf2ae157e5053fe1552",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":35,
                  "y":437},
                "size":{
                  "width":320,
                  "height":33},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/签到/u73.png"}},
{
          "id":"2e18725e048f4e9a825258cecc967e1d",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"12px",
            "fontWeight":"400",
            "location":{
              "x":49,
              "y":446},
            "size":{
              "width":211,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"41e8efdceda24366a7d5d063e72321ff",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"12px",
                "fontWeight":"400",
                "location":{
                  "x":49,
                  "y":446},
                "size":{
                  "width":211,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9aeb5044b76d4cccb9940677dfcd83af",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"12px",
            "fontWeight":"400",
            "location":{
              "x":49,
              "y":476},
            "size":{
              "width":138,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2dac4a737bc04502b54f3b2be4af4903",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"12px",
                "fontWeight":"400",
                "location":{
                  "x":49,
                  "y":476},
                "size":{
                  "width":138,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e656eb60e9e940a59f5184ef1e433535",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":329,
              "y":477},
            "size":{
              "width":10,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b670fd54bd724d638490c9d4df060f23",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":329,
                  "y":477},
                "size":{
                  "width":10,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"19822f71dbad428fae81904dcc9fb4e8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":329,
              "y":445},
            "size":{
              "width":10,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2b166c27885d4d5fb2b67766e9b53c48",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":329,
                  "y":445},
                "size":{
                  "width":10,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
    "0b7481d9291846af9389708a818f6ee6":{
      "packageId":"0b7481d9291846af9389708a818f6ee6",
      "type":"Axure:Master",
      "name":"手机",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"f1dfbdea093d41b09735aae262127399",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "size":{
                "width":388,
                "height":720},
              "borderWidth":"3",
              "borderFill":{
                "fillType":"solid",
                "color":0xFFCCCCCC},
              "cornerRadiusTopLeft":"23"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"54ce0076fc284f268413b560877042f3",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":388,
                    "height":720},
                  "borderWidth":"3",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFCCCCCC},
                  "cornerRadiusTopLeft":"23"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/登录/u1.png"}},
{
            "id":"ab9e31cf23e142ee94d04b46c74b970e",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFFF2F2F2},
              "location":{
                "x":36,
                "y":91},
              "size":{
                "width":320,
                "height":480},
              "borderWidth":"-1",
              "borderFill":{
                "fillType":"solid",
                "color":0xFFFFFF}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"3ab26a5565ea402f9f26e370e766ab77",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFF2F2F2},
                  "location":{
                    "x":36,
                    "y":91},
                  "size":{
                    "width":320,
                    "height":480},
                  "borderWidth":"-1",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFFFFF}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/登录/u3.png"}},
{
            "id":"778d1d4e585c4b1999a8a13f41c86394",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFF333333},
              "location":{
                "x":36,
                "y":91},
              "size":{
                "width":320,
                "height":20},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFFFFF}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"6393b6169e4944b0a5bacb6e7876f663",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF333333},
                  "location":{
                    "x":36,
                    "y":91},
                  "size":{
                    "width":320,
                    "height":20},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFFFFF}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/登录/u5.png"}},
{
            "id":"82466aad239343fd99ca0aa832fce046",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFFF2F2F2},
              "location":{
                "x":159,
                "y":610},
              "size":{
                "width":60,
                "height":61},
              "borderWidth":"3",
              "borderFill":{
                "fillType":"solid",
                "color":0xFFCCCCCC},
              "cornerRadiusTopLeft":"100"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"449f01aeeeb24531a1c8210ccbb014cc",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFF2F2F2},
                  "location":{
                    "x":159,
                    "y":610},
                  "size":{
                    "width":60,
                    "height":61},
                  "borderWidth":"3",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFCCCCCC},
                  "cornerRadiusTopLeft":"100"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/登录/u7.png"}},
{
            "id":"3961b32dcc1a40fcbc6bfd22d98eeae2",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFF999999},
              "location":{
                "x":179,
                "y":631},
              "size":{
                "width":20,
                "height":20},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFFFFF},
              "cornerRadiusTopLeft":"4"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"7b559f9ed3de40848129dd2ad0bc1939",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF999999},
                  "location":{
                    "x":179,
                    "y":631},
                  "size":{
                    "width":20,
                    "height":20},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFFFFF},
                  "cornerRadiusTopLeft":"4"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/登录/u9.png"}},
{
            "id":"30ab91e377a6423ab81eff19444f2d2a",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"12px",
              "horizontalAlignment":"center",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "location":{
                "x":164,
                "y":94},
              "size":{
                "width":75,
                "height":15},
              "rotation":"0",
              "textRotation":"0"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"b41c87afa21f477ea7270b37c48e7eff",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"12px",
                  "horizontalAlignment":"center",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "location":{
                    "x":164,
                    "y":94},
                  "size":{
                    "width":75,
                    "height":15},
                  "rotation":"0",
                  "textRotation":"0"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"af1cf1fd332945d298cfea08298ec3ea",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":323,
                "y":95},
              "size":{
                "width":22,
                "height":11},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFFFFF}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"a2ce34bd582a4f0d973a5b715165689d",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":323,
                    "y":95},
                  "size":{
                    "width":22,
                    "height":11},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFFFFF}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/登录/u13.png"}},
{
            "id":"1b60a919ae904b59919e6507de351e77",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":345,
                "y":98},
              "size":{
                "width":4,
                "height":5},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFFFFF},
              "cornerRadiusTopLeft":"1"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"94059979496c45349791a403f98024ed",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":345,
                    "y":98},
                  "size":{
                    "width":4,
                    "height":5},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFFFFF},
                  "cornerRadiusTopLeft":"1"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/登录/u15.png"}},
{
            "id":"25da23a08fcb444cbbf1fc72394fd476",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"11px",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "location":{
                "x":43,
                "y":94},
              "size":{
                "width":82,
                "height":14},
              "rotation":"0",
              "textRotation":"0"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"b78d3bea065748e6888c0f75e83057ed",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"11px",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "location":{
                    "x":43,
                    "y":94},
                  "size":{
                    "width":82,
                    "height":14},
                  "rotation":"0",
                  "textRotation":"0"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"8b2e58b05d324d178a80af84d5a955a9",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFF999999},
              "location":{
                "x":174,
                "y":64},
              "size":{
                "width":50,
                "height":8},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFFFFF},
              "cornerRadiusTopLeft":"6"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"cfe4a760e0c9478db90a300bb7258014",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF999999},
                  "location":{
                    "x":174,
                    "y":64},
                  "size":{
                    "width":50,
                    "height":8},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFFFFF},
                  "cornerRadiusTopLeft":"6"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/登录/u19.png"}},
{
            "id":"598708d1af384602b9a84271fd9fb443",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFF999999},
              "location":{
                "x":195,
                "y":50},
              "size":{
                "width":10,
                "height":10},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFFFFF},
              "cornerRadiusTopLeft":"8"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"bcd9c014b42141d2991ecfeecdfa8069",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF999999},
                  "location":{
                    "x":195,
                    "y":50},
                  "size":{
                    "width":10,
                    "height":10},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFFFFF},
                  "cornerRadiusTopLeft":"8"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/登录/u21.png"}}]}},
    "f85a4329c07a4f10882ec32eccff2b14":{
      "packageId":"f85a4329c07a4f10882ec32eccff2b14",
      "type":"Axure:Master",
      "name":"奖品",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"db0a5001a475412aa6e792ddd04537e7",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "size":{
                "width":90,
                "height":91},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFCCCCCC}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"7c564d81b48b47dca00549f1f8fcd8a3",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":90,
                    "height":91},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFCCCCCC}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/签到/u32.png",
              "normal~":"images/签到/u32.png",
              "normal~":"images/签到/u32.png",
              "normal~":"images/签到/u32.png",
              "normal~":"images/签到/u32.png",
              "normal~":"images/签到/u32.png"}},
{
            "id":"6c411a0dcba745808cf90c760f8b9dc5",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"14px",
              "location":{
                "x":0,
                "y":115},
              "size":{
                "width":51,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"f0aa418cc17f4823935ca17d0a5485c5",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"14px",
                  "location":{
                    "x":0,
                    "y":115},
                  "size":{
                    "width":51,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif",
              "normal~":"resources/images/transparent.gif",
              "normal~":"resources/images/transparent.gif",
              "normal~":"resources/images/transparent.gif",
              "normal~":"resources/images/transparent.gif",
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"dedab6ecb9ba413d8c704fca70c960fb",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'Arial Negreta', 'Arial'",
              "fontWeight":"700",
              "location":{
                "x":0,
                "y":94},
              "size":{
                "width":90,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"d7ae8a4102844a56a775753840d118d7",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial Negreta', 'Arial'",
                  "fontWeight":"700",
                  "location":{
                    "x":0,
                    "y":94},
                  "size":{
                    "width":90,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif",
              "normal~":"resources/images/transparent.gif",
              "normal~":"resources/images/transparent.gif",
              "normal~":"resources/images/transparent.gif",
              "normal~":"resources/images/transparent.gif",
              "normal~":"resources/images/transparent.gif"}}]}}},
  "objectPaths":{
    "5ae154e2bfb147889c163f746441d7f1":{
      "scriptId":"u0",
      "f1dfbdea093d41b09735aae262127399":{
        "scriptId":"u1"},
      "54ce0076fc284f268413b560877042f3":{
        "scriptId":"u2"},
      "ab9e31cf23e142ee94d04b46c74b970e":{
        "scriptId":"u3"},
      "3ab26a5565ea402f9f26e370e766ab77":{
        "scriptId":"u4"},
      "778d1d4e585c4b1999a8a13f41c86394":{
        "scriptId":"u5"},
      "6393b6169e4944b0a5bacb6e7876f663":{
        "scriptId":"u6"},
      "82466aad239343fd99ca0aa832fce046":{
        "scriptId":"u7"},
      "449f01aeeeb24531a1c8210ccbb014cc":{
        "scriptId":"u8"},
      "3961b32dcc1a40fcbc6bfd22d98eeae2":{
        "scriptId":"u9"},
      "7b559f9ed3de40848129dd2ad0bc1939":{
        "scriptId":"u10"},
      "30ab91e377a6423ab81eff19444f2d2a":{
        "scriptId":"u11"},
      "b41c87afa21f477ea7270b37c48e7eff":{
        "scriptId":"u12"},
      "af1cf1fd332945d298cfea08298ec3ea":{
        "scriptId":"u13"},
      "a2ce34bd582a4f0d973a5b715165689d":{
        "scriptId":"u14"},
      "1b60a919ae904b59919e6507de351e77":{
        "scriptId":"u15"},
      "94059979496c45349791a403f98024ed":{
        "scriptId":"u16"},
      "25da23a08fcb444cbbf1fc72394fd476":{
        "scriptId":"u17"},
      "b78d3bea065748e6888c0f75e83057ed":{
        "scriptId":"u18"},
      "8b2e58b05d324d178a80af84d5a955a9":{
        "scriptId":"u19"},
      "cfe4a760e0c9478db90a300bb7258014":{
        "scriptId":"u20"},
      "598708d1af384602b9a84271fd9fb443":{
        "scriptId":"u21"},
      "bcd9c014b42141d2991ecfeecdfa8069":{
        "scriptId":"u22"}},
    "19af92c1bce942cfab26abcbe68a41f4":{
      "scriptId":"u23"},
    "000616cdd8ab44ef9fc69aa09ea6a863":{
      "scriptId":"u24"},
    "1d5f27f3520548a3b0ef938c3532057b":{
      "scriptId":"u25"},
    "8160509f98c744d095abf2b648fda92b":{
      "scriptId":"u26"},
    "1ab4f992ca694fdc9dbe9d975f959b85":{
      "scriptId":"u27"},
    "4653fd15eb624d4aba317287cc6644fb":{
      "scriptId":"u28"},
    "156ce192fc1d48e681b7492786357600":{
      "scriptId":"u29"},
    "af9427778fbb4e339a02db2a1e2b4cea":{
      "scriptId":"u30"},
    "0cf06ef0da944752b35e869e4f6ac7d2":{
      "scriptId":"u31",
      "db0a5001a475412aa6e792ddd04537e7":{
        "scriptId":"u32"},
      "7c564d81b48b47dca00549f1f8fcd8a3":{
        "scriptId":"u33"},
      "6c411a0dcba745808cf90c760f8b9dc5":{
        "scriptId":"u34"},
      "f0aa418cc17f4823935ca17d0a5485c5":{
        "scriptId":"u35"},
      "dedab6ecb9ba413d8c704fca70c960fb":{
        "scriptId":"u36"},
      "d7ae8a4102844a56a775753840d118d7":{
        "scriptId":"u37"}},
    "15eee5174e4a47c48f6833f80d9ebdb7":{
      "scriptId":"u38",
      "db0a5001a475412aa6e792ddd04537e7":{
        "scriptId":"u39"},
      "7c564d81b48b47dca00549f1f8fcd8a3":{
        "scriptId":"u40"},
      "6c411a0dcba745808cf90c760f8b9dc5":{
        "scriptId":"u41"},
      "f0aa418cc17f4823935ca17d0a5485c5":{
        "scriptId":"u42"},
      "dedab6ecb9ba413d8c704fca70c960fb":{
        "scriptId":"u43"},
      "d7ae8a4102844a56a775753840d118d7":{
        "scriptId":"u44"}},
    "67393dcfc1144f2397e7c9cf36a47f05":{
      "scriptId":"u45",
      "db0a5001a475412aa6e792ddd04537e7":{
        "scriptId":"u46"},
      "7c564d81b48b47dca00549f1f8fcd8a3":{
        "scriptId":"u47"},
      "6c411a0dcba745808cf90c760f8b9dc5":{
        "scriptId":"u48"},
      "f0aa418cc17f4823935ca17d0a5485c5":{
        "scriptId":"u49"},
      "dedab6ecb9ba413d8c704fca70c960fb":{
        "scriptId":"u50"},
      "d7ae8a4102844a56a775753840d118d7":{
        "scriptId":"u51"}},
    "0953079bca41407987efd8eca4aedfa7":{
      "scriptId":"u52",
      "db0a5001a475412aa6e792ddd04537e7":{
        "scriptId":"u53"},
      "7c564d81b48b47dca00549f1f8fcd8a3":{
        "scriptId":"u54"},
      "6c411a0dcba745808cf90c760f8b9dc5":{
        "scriptId":"u55"},
      "f0aa418cc17f4823935ca17d0a5485c5":{
        "scriptId":"u56"},
      "dedab6ecb9ba413d8c704fca70c960fb":{
        "scriptId":"u57"},
      "d7ae8a4102844a56a775753840d118d7":{
        "scriptId":"u58"}},
    "882aba52073741bb9973cf0daf2d44fb":{
      "scriptId":"u59",
      "db0a5001a475412aa6e792ddd04537e7":{
        "scriptId":"u60"},
      "7c564d81b48b47dca00549f1f8fcd8a3":{
        "scriptId":"u61"},
      "6c411a0dcba745808cf90c760f8b9dc5":{
        "scriptId":"u62"},
      "f0aa418cc17f4823935ca17d0a5485c5":{
        "scriptId":"u63"},
      "dedab6ecb9ba413d8c704fca70c960fb":{
        "scriptId":"u64"},
      "d7ae8a4102844a56a775753840d118d7":{
        "scriptId":"u65"}},
    "bc1a276a736c4c5b8a3faf7a6e3b1207":{
      "scriptId":"u66",
      "db0a5001a475412aa6e792ddd04537e7":{
        "scriptId":"u67"},
      "7c564d81b48b47dca00549f1f8fcd8a3":{
        "scriptId":"u68"},
      "6c411a0dcba745808cf90c760f8b9dc5":{
        "scriptId":"u69"},
      "f0aa418cc17f4823935ca17d0a5485c5":{
        "scriptId":"u70"},
      "dedab6ecb9ba413d8c704fca70c960fb":{
        "scriptId":"u71"},
      "d7ae8a4102844a56a775753840d118d7":{
        "scriptId":"u72"}},
    "92e11fca761e47bcb69a696634203c06":{
      "scriptId":"u73"},
    "e4db0ee050494b8499b2e7cc793e8e53":{
      "scriptId":"u74"},
    "c77e01020057420784f8e8764f806fbe":{
      "scriptId":"u75"},
    "2e402407502b4bf2ae157e5053fe1552":{
      "scriptId":"u76"},
    "2e18725e048f4e9a825258cecc967e1d":{
      "scriptId":"u77"},
    "41e8efdceda24366a7d5d063e72321ff":{
      "scriptId":"u78"},
    "9aeb5044b76d4cccb9940677dfcd83af":{
      "scriptId":"u79"},
    "2dac4a737bc04502b54f3b2be4af4903":{
      "scriptId":"u80"},
    "e656eb60e9e940a59f5184ef1e433535":{
      "scriptId":"u81"},
    "b670fd54bd724d638490c9d4df060f23":{
      "scriptId":"u82"},
    "19822f71dbad428fae81904dcc9fb4e8":{
      "scriptId":"u83"},
    "2b166c27885d4d5fb2b67766e9b53c48":{
      "scriptId":"u84"}}});