pod 'AFNetworking', '~> 2.5.4'          
pod 'SDWebImage', '~> 3.7.3'             
pod 'CocoaLumberjack', '~> 2.0.1'       
pod 'SVProgressHUD', '~> 1.1.3'        
pod 'MJRefresh', '~> 2.3.1'            
pod 'AFDownloadRequestOperation', '~> 2.0.1'
pod 'DDPageControl', '~> 0.1'
pod 'FLEX', '~> 2.0.3'
pod 'CocoaLumberjack', '~> 2.0.1'
pod 'SIAlertView'