$axure.loadCurrentPage({
  "url":"系统设置.html",
  "generationDate":new Date(1438070191725.03),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"9a5cf38e49d542b38489657f77b099c1",
    "type":"Axure:Page",
    "name":"系统设置",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"11b99a277e1449b2aba340eee05015b6",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"0b7481d9291846af9389708a818f6ee6"},
{
          "id":"7acce8d22f0044eb8a476e0d3abe5ca8",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":36,
              "y":109},
            "size":{
              "width":320,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"41ff958213444a748958c4628e69a4dc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":36,
                  "y":109},
                "size":{
                  "width":320,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注册/u23.png"}},
{
          "id":"e8e9a9dd562248e8ae1d522ace12eb8d",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":47,
              "y":120},
            "size":{
              "width":18,
              "height":18},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8210413fc7bd413e99895841cb1e7313",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":47,
                  "y":120},
                "size":{
                  "width":18,
                  "height":18},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 我",
                      "target":{
                        "targetType":"page",
                        "url":"我.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/注册/u25.png"}},
{
          "id":"06823947114b451baf95c339cfb9345c",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":36,
              "y":191},
            "size":{
              "width":320,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/系统设置/u27_line.png"}},
{
          "id":"41782238b6314f4986cb9dadcf030737",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF333333},
            "location":{
              "x":280,
              "y":159},
            "size":{
              "width":70,
              "height":32},
            "cornerRadiusTopLeft":"6"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"563f69cc3c7f441492c0200684e519eb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF333333},
                "location":{
                  "x":280,
                  "y":159},
                "size":{
                  "width":70,
                  "height":32},
                "cornerRadiusTopLeft":"6"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/系统设置/u28.png"}},
{
          "id":"81ad1e4fd8304b22bd259e04aa0be6e9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "location":{
              "x":52,
              "y":165},
            "size":{
              "width":99,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"92cd792650c74a84905b0fea300f5b68",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "location":{
                  "x":52,
                  "y":165},
                "size":{
                  "width":99,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f0982c9aa83a49649b831da13725e84d",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":290,
              "y":202}},
          "adaptiveStyles":{
},
          "masterId":"8e3df450008b433d9a0ab5d28976614e"},
{
          "id":"06fa3d5a75464c8ab6267caf081c9e08",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "location":{
              "x":52,
              "y":211},
            "size":{
              "width":138,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c6ab7684331d44eda64ec7bcf81d2508",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "location":{
                  "x":52,
                  "y":211},
                "size":{
                  "width":138,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"77c896d0c21a4410ac5a4e13ab088c30",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF333333},
            "location":{
              "x":49,
              "y":510},
            "size":{
              "width":290,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"8"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6007cc50370a432d842c425b58e5063f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF333333},
                "location":{
                  "x":49,
                  "y":510},
                "size":{
                  "width":290,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"8"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 登录",
                      "target":{
                        "targetType":"page",
                        "url":"登录.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/系统设置/u39.png"}},
{
          "id":"6bfa912ecef449bcb595d313577879c5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "location":{
              "x":52,
              "y":263},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"917873bc5e31499885b0968893140d30",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "location":{
                  "x":52,
                  "y":263},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1231d8085b224770af14229d45c882a5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "location":{
              "x":320,
              "y":263},
            "size":{
              "width":20,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f8a7b9d619cf4358bca35eea87814549",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "location":{
                  "x":320,
                  "y":263},
                "size":{
                  "width":20,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"797c43e9247d43f09f3a75b767ca73d2",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":36,
              "y":243},
            "size":{
              "width":320,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/系统设置/u27_line.png"}},
{
          "id":"f8db1d70c1124776ad7bd364321ff5ca",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "location":{
              "x":52,
              "y":313},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"876d1707a90442128e6ea615ec09faf0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "location":{
                  "x":52,
                  "y":313},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 关于我们",
                      "target":{
                        "targetType":"page",
                        "url":"关于我们.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b66c8586b4674411b0104b7f3bf0f318",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "location":{
              "x":320,
              "y":310},
            "size":{
              "width":20,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6653241e244a4fdea5d5a032660d6000",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "location":{
                  "x":320,
                  "y":310},
                "size":{
                  "width":20,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f5177e356bd14cdcab236bf5ed8034a9",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":36,
              "y":290},
            "size":{
              "width":320,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/系统设置/u27_line.png"}},
{
          "id":"5ddea3839be24c9fb5eb71313dec2ff8",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":36,
              "y":339},
            "size":{
              "width":320,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/系统设置/u27_line.png"}}]}},
  "masters":{
    "0b7481d9291846af9389708a818f6ee6":{
      "packageId":"0b7481d9291846af9389708a818f6ee6",
      "type":"Axure:Master",
      "name":"手机",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"f1dfbdea093d41b09735aae262127399",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "size":{
                "width":388,
                "height":720},
              "borderWidth":"3",
              "borderFill":{
                "fillType":"solid",
                "color":0xFFCCCCCC},
              "cornerRadiusTopLeft":"23"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"54ce0076fc284f268413b560877042f3",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":388,
                    "height":720},
                  "borderWidth":"3",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFCCCCCC},
                  "cornerRadiusTopLeft":"23"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/登录/u1.png"}},
{
            "id":"ab9e31cf23e142ee94d04b46c74b970e",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFFF2F2F2},
              "location":{
                "x":36,
                "y":91},
              "size":{
                "width":320,
                "height":480},
              "borderWidth":"-1",
              "borderFill":{
                "fillType":"solid",
                "color":0xFFFFFF}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"3ab26a5565ea402f9f26e370e766ab77",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFF2F2F2},
                  "location":{
                    "x":36,
                    "y":91},
                  "size":{
                    "width":320,
                    "height":480},
                  "borderWidth":"-1",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFFFFF}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/登录/u3.png"}},
{
            "id":"778d1d4e585c4b1999a8a13f41c86394",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFF333333},
              "location":{
                "x":36,
                "y":91},
              "size":{
                "width":320,
                "height":20},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFFFFF}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"6393b6169e4944b0a5bacb6e7876f663",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF333333},
                  "location":{
                    "x":36,
                    "y":91},
                  "size":{
                    "width":320,
                    "height":20},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFFFFF}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/登录/u5.png"}},
{
            "id":"82466aad239343fd99ca0aa832fce046",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFFF2F2F2},
              "location":{
                "x":159,
                "y":610},
              "size":{
                "width":60,
                "height":61},
              "borderWidth":"3",
              "borderFill":{
                "fillType":"solid",
                "color":0xFFCCCCCC},
              "cornerRadiusTopLeft":"100"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"449f01aeeeb24531a1c8210ccbb014cc",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFF2F2F2},
                  "location":{
                    "x":159,
                    "y":610},
                  "size":{
                    "width":60,
                    "height":61},
                  "borderWidth":"3",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFCCCCCC},
                  "cornerRadiusTopLeft":"100"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/登录/u7.png"}},
{
            "id":"3961b32dcc1a40fcbc6bfd22d98eeae2",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFF999999},
              "location":{
                "x":179,
                "y":631},
              "size":{
                "width":20,
                "height":20},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFFFFF},
              "cornerRadiusTopLeft":"4"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"7b559f9ed3de40848129dd2ad0bc1939",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF999999},
                  "location":{
                    "x":179,
                    "y":631},
                  "size":{
                    "width":20,
                    "height":20},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFFFFF},
                  "cornerRadiusTopLeft":"4"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/登录/u9.png"}},
{
            "id":"30ab91e377a6423ab81eff19444f2d2a",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"12px",
              "horizontalAlignment":"center",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "location":{
                "x":164,
                "y":94},
              "size":{
                "width":75,
                "height":15},
              "rotation":"0",
              "textRotation":"0"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"b41c87afa21f477ea7270b37c48e7eff",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"12px",
                  "horizontalAlignment":"center",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "location":{
                    "x":164,
                    "y":94},
                  "size":{
                    "width":75,
                    "height":15},
                  "rotation":"0",
                  "textRotation":"0"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"af1cf1fd332945d298cfea08298ec3ea",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":323,
                "y":95},
              "size":{
                "width":22,
                "height":11},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFFFFF}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"a2ce34bd582a4f0d973a5b715165689d",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":323,
                    "y":95},
                  "size":{
                    "width":22,
                    "height":11},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFFFFF}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/登录/u13.png"}},
{
            "id":"1b60a919ae904b59919e6507de351e77",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":345,
                "y":98},
              "size":{
                "width":4,
                "height":5},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFFFFF},
              "cornerRadiusTopLeft":"1"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"94059979496c45349791a403f98024ed",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":345,
                    "y":98},
                  "size":{
                    "width":4,
                    "height":5},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFFFFF},
                  "cornerRadiusTopLeft":"1"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/登录/u15.png"}},
{
            "id":"25da23a08fcb444cbbf1fc72394fd476",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"11px",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "location":{
                "x":43,
                "y":94},
              "size":{
                "width":82,
                "height":14},
              "rotation":"0",
              "textRotation":"0"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"b78d3bea065748e6888c0f75e83057ed",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"11px",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "location":{
                    "x":43,
                    "y":94},
                  "size":{
                    "width":82,
                    "height":14},
                  "rotation":"0",
                  "textRotation":"0"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"8b2e58b05d324d178a80af84d5a955a9",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFF999999},
              "location":{
                "x":174,
                "y":64},
              "size":{
                "width":50,
                "height":8},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFFFFF},
              "cornerRadiusTopLeft":"6"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"cfe4a760e0c9478db90a300bb7258014",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF999999},
                  "location":{
                    "x":174,
                    "y":64},
                  "size":{
                    "width":50,
                    "height":8},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFFFFF},
                  "cornerRadiusTopLeft":"6"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/登录/u19.png"}},
{
            "id":"598708d1af384602b9a84271fd9fb443",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFF999999},
              "location":{
                "x":195,
                "y":50},
              "size":{
                "width":10,
                "height":10},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFFFFF},
              "cornerRadiusTopLeft":"8"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"bcd9c014b42141d2991ecfeecdfa8069",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF999999},
                  "location":{
                    "x":195,
                    "y":50},
                  "size":{
                    "width":10,
                    "height":10},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFFFFF},
                  "cornerRadiusTopLeft":"8"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/登录/u21.png"}}]}},
    "8e3df450008b433d9a0ab5d28976614e":{
      "packageId":"8e3df450008b433d9a0ab5d28976614e",
      "type":"Axure:Master",
      "name":"开关键",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"691ab28be5c34962b4ff10f785ab037a",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFFF2F2F2},
              "location":{
                "x":0,
                "y":1},
              "size":{
                "width":60,
                "height":30},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFE4E4E4},
              "cornerRadiusTopLeft":"42"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"6062ae2bae3e4979b99e69adc8435843",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFF2F2F2},
                  "location":{
                    "x":0,
                    "y":1},
                  "size":{
                    "width":60,
                    "height":30},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFE4E4E4},
                  "cornerRadiusTopLeft":"42"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/系统设置/u33.png"}},
{
            "id":"f683f1a8665c44bb9122099489a5290e",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":28,
                "y":0},
              "size":{
                "width":30,
                "height":30},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFFFFF},
              "cornerRadiusTopLeft":"20",
              "outerShadow":{
                "on":true,
                "offsetX":2,
                "offsetY":2,
                "blurRadius":5,
                "color":{
                  "r":0,
                  "g":0,
                  "b":0,
                  "a":0.349019607843137}}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"8e20dfd052354ff6bfeebb4b2a7783bc",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":28,
                    "y":0},
                  "size":{
                    "width":30,
                    "height":30},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFFFFF},
                  "cornerRadiusTopLeft":"20",
                  "outerShadow":{
                    "on":true,
                    "offsetX":2,
                    "offsetY":2,
                    "blurRadius":5,
                    "color":{
                      "r":0,
                      "g":0,
                      "b":0,
                      "a":0.349019607843137}}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/系统设置/u35.png"}}]}}},
  "objectPaths":{
    "11b99a277e1449b2aba340eee05015b6":{
      "scriptId":"u0",
      "f1dfbdea093d41b09735aae262127399":{
        "scriptId":"u1"},
      "54ce0076fc284f268413b560877042f3":{
        "scriptId":"u2"},
      "ab9e31cf23e142ee94d04b46c74b970e":{
        "scriptId":"u3"},
      "3ab26a5565ea402f9f26e370e766ab77":{
        "scriptId":"u4"},
      "778d1d4e585c4b1999a8a13f41c86394":{
        "scriptId":"u5"},
      "6393b6169e4944b0a5bacb6e7876f663":{
        "scriptId":"u6"},
      "82466aad239343fd99ca0aa832fce046":{
        "scriptId":"u7"},
      "449f01aeeeb24531a1c8210ccbb014cc":{
        "scriptId":"u8"},
      "3961b32dcc1a40fcbc6bfd22d98eeae2":{
        "scriptId":"u9"},
      "7b559f9ed3de40848129dd2ad0bc1939":{
        "scriptId":"u10"},
      "30ab91e377a6423ab81eff19444f2d2a":{
        "scriptId":"u11"},
      "b41c87afa21f477ea7270b37c48e7eff":{
        "scriptId":"u12"},
      "af1cf1fd332945d298cfea08298ec3ea":{
        "scriptId":"u13"},
      "a2ce34bd582a4f0d973a5b715165689d":{
        "scriptId":"u14"},
      "1b60a919ae904b59919e6507de351e77":{
        "scriptId":"u15"},
      "94059979496c45349791a403f98024ed":{
        "scriptId":"u16"},
      "25da23a08fcb444cbbf1fc72394fd476":{
        "scriptId":"u17"},
      "b78d3bea065748e6888c0f75e83057ed":{
        "scriptId":"u18"},
      "8b2e58b05d324d178a80af84d5a955a9":{
        "scriptId":"u19"},
      "cfe4a760e0c9478db90a300bb7258014":{
        "scriptId":"u20"},
      "598708d1af384602b9a84271fd9fb443":{
        "scriptId":"u21"},
      "bcd9c014b42141d2991ecfeecdfa8069":{
        "scriptId":"u22"}},
    "7acce8d22f0044eb8a476e0d3abe5ca8":{
      "scriptId":"u23"},
    "41ff958213444a748958c4628e69a4dc":{
      "scriptId":"u24"},
    "e8e9a9dd562248e8ae1d522ace12eb8d":{
      "scriptId":"u25"},
    "8210413fc7bd413e99895841cb1e7313":{
      "scriptId":"u26"},
    "06823947114b451baf95c339cfb9345c":{
      "scriptId":"u27"},
    "41782238b6314f4986cb9dadcf030737":{
      "scriptId":"u28"},
    "563f69cc3c7f441492c0200684e519eb":{
      "scriptId":"u29"},
    "81ad1e4fd8304b22bd259e04aa0be6e9":{
      "scriptId":"u30"},
    "92cd792650c74a84905b0fea300f5b68":{
      "scriptId":"u31"},
    "f0982c9aa83a49649b831da13725e84d":{
      "scriptId":"u32",
      "691ab28be5c34962b4ff10f785ab037a":{
        "scriptId":"u33"},
      "6062ae2bae3e4979b99e69adc8435843":{
        "scriptId":"u34"},
      "f683f1a8665c44bb9122099489a5290e":{
        "scriptId":"u35"},
      "8e20dfd052354ff6bfeebb4b2a7783bc":{
        "scriptId":"u36"}},
    "06fa3d5a75464c8ab6267caf081c9e08":{
      "scriptId":"u37"},
    "c6ab7684331d44eda64ec7bcf81d2508":{
      "scriptId":"u38"},
    "77c896d0c21a4410ac5a4e13ab088c30":{
      "scriptId":"u39"},
    "6007cc50370a432d842c425b58e5063f":{
      "scriptId":"u40"},
    "6bfa912ecef449bcb595d313577879c5":{
      "scriptId":"u41"},
    "917873bc5e31499885b0968893140d30":{
      "scriptId":"u42"},
    "1231d8085b224770af14229d45c882a5":{
      "scriptId":"u43"},
    "f8a7b9d619cf4358bca35eea87814549":{
      "scriptId":"u44"},
    "797c43e9247d43f09f3a75b767ca73d2":{
      "scriptId":"u45"},
    "f8db1d70c1124776ad7bd364321ff5ca":{
      "scriptId":"u46"},
    "876d1707a90442128e6ea615ec09faf0":{
      "scriptId":"u47"},
    "b66c8586b4674411b0104b7f3bf0f318":{
      "scriptId":"u48"},
    "6653241e244a4fdea5d5a032660d6000":{
      "scriptId":"u49"},
    "f5177e356bd14cdcab236bf5ed8034a9":{
      "scriptId":"u50"},
    "5ddea3839be24c9fb5eb71313dec2ff8":{
      "scriptId":"u51"}}});