$axure.loadCurrentPage({
  "url":"我的优惠券.html",
  "generationDate":new Date(1438070191533.02),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"28ff3627ef4c4c679f2012fc46401d2a",
    "type":"Axure:Page",
    "name":"我的优惠券",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"b3b270ce980d4a5db65c5a42205fb823",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"0b7481d9291846af9389708a818f6ee6"},
{
          "id":"f127333ab6a04bc6858ad4e5b8c4bc6c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":36,
              "y":109},
            "size":{
              "width":320,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"38a13410c60a4ba3b6489b3061d2939e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":36,
                  "y":109},
                "size":{
                  "width":320,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注册/u23.png"}},
{
          "id":"afdd9cf122b6459c9cb9f57de50d3f13",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":47,
              "y":120},
            "size":{
              "width":18,
              "height":18},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6a450eecfba84edbb71966a277b5f9a0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":47,
                  "y":120},
                "size":{
                  "width":18,
                  "height":18},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 我",
                      "target":{
                        "targetType":"page",
                        "url":"我.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/注册/u25.png"}},
{
          "id":"4c4e13f5128d4234b439b27c4ddd241a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":48,
              "y":326},
            "size":{
              "width":300,
              "height":76},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "cornerRadiusTopLeft":"10"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"94984e12485f4158a6c9be81858bc5ab",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":48,
                  "y":326},
                "size":{
                  "width":300,
                  "height":76},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "cornerRadiusTopLeft":"10"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/优惠券/u43.png"}},
{
          "id":"a67e66872150435ab354e126f91aaaf0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":123,
              "y":378},
            "size":{
              "width":127,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9fa1b4e27b974c7f8960d07f53b9c4e7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":123,
                  "y":378},
                "size":{
                  "width":127,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4d539fb245df49bcb52ceb389b915e3f",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":60,
              "y":343},
            "size":{
              "width":50,
              "height":44},
            "borderWidth":"1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "cornerRadiusTopLeft":"71"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dca5fe91d99c41baaf3dd1304fdc8275",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":60,
                  "y":343},
                "size":{
                  "width":50,
                  "height":44},
                "borderWidth":"1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "cornerRadiusTopLeft":"71"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/优惠券/u47.png"}},
{
          "id":"c1dfb64f0c30457ea1a1fc84c19066ee",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"700",
            "location":{
              "x":123,
              "y":335},
            "size":{
              "width":83,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a4ba53a9b4e14fa8be39a0bb5a4c573c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"700",
                "location":{
                  "x":123,
                  "y":335},
                "size":{
                  "width":83,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 优惠券详情",
                      "target":{
                        "targetType":"page",
                        "url":"优惠券详情_1.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"50dc5e45acaa435fb726cd178daa82b5",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":289,
              "y":353},
            "size":{
              "width":33,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0576fcc5f7514b73849a5cd9df63a759",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":289,
                  "y":353},
                "size":{
                  "width":33,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"abf54b06f94e4a92a1d60ac3fbffdfbc",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":261,
              "y":340},
            "size":{
              "width":10,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/优惠券/u53_line.png"}},
{
          "id":"7685fae8b23647109bec2d0a5a5bb2f8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":123,
              "y":360},
            "size":{
              "width":59,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"86ea8324eaba4e86b3bbd76bdb262d9e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":123,
                  "y":360},
                "size":{
                  "width":59,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1c3fb17113f14ddea13ffe4f9eaaf045",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":48,
              "y":161},
            "size":{
              "width":300,
              "height":76},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "cornerRadiusTopLeft":"10"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"441a577d62b64fcdb65ee1c68a5f3219",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":48,
                  "y":161},
                "size":{
                  "width":300,
                  "height":76},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "cornerRadiusTopLeft":"10"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/优惠券/u43.png"}},
{
          "id":"4a3fb40b368241e39258c50f844313eb",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":123,
              "y":213},
            "size":{
              "width":127,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"82b1202be2cd4e04af619dbfc747cafa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":123,
                  "y":213},
                "size":{
                  "width":127,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a7e37d1ed2c5432999fe4772f41b8048",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":60,
              "y":178},
            "size":{
              "width":50,
              "height":44},
            "borderWidth":"1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "cornerRadiusTopLeft":"71"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c8a7b6e1738c4988bcb541f0eed5c0f5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":60,
                  "y":178},
                "size":{
                  "width":50,
                  "height":44},
                "borderWidth":"1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "cornerRadiusTopLeft":"71"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/优惠券/u47.png"}},
{
          "id":"6904f36601f84db288c0b21fe2800e75",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"700",
            "location":{
              "x":123,
              "y":170},
            "size":{
              "width":83,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d3c0481c1636492fae9d4bff13579915",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"700",
                "location":{
                  "x":123,
                  "y":170},
                "size":{
                  "width":83,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 优惠券详情",
                      "target":{
                        "targetType":"page",
                        "url":"优惠券详情_1.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6ebbb1596df44819b1d3c8553b89ea79",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":289,
              "y":188},
            "size":{
              "width":33,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4cbfe69335af4b769cc53308476e2006",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":289,
                  "y":188},
                "size":{
                  "width":33,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"15681647c78041a49f7df225d4720551",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":261,
              "y":175},
            "size":{
              "width":10,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/优惠券/u53_line.png"}},
{
          "id":"ade5b2dfe1624460a8a100630c63d37f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":123,
              "y":195},
            "size":{
              "width":59,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b6e046a088ae43b09a4080afe6249ec3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":123,
                  "y":195},
                "size":{
                  "width":59,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"056e789f96704061926d58a233512a49",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":48,
              "y":243},
            "size":{
              "width":300,
              "height":76},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "cornerRadiusTopLeft":"10"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"66fe7e3301e14b24a1ab71e3358fb54a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":48,
                  "y":243},
                "size":{
                  "width":300,
                  "height":76},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "cornerRadiusTopLeft":"10"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/优惠券/u43.png"}},
{
          "id":"9bb85b1b17f54153a1cee4134503bf81",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":123,
              "y":295},
            "size":{
              "width":127,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cbf9fdba8061481ca15123934645e024",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":123,
                  "y":295},
                "size":{
                  "width":127,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fdd9845d123c472c8793f0bcc2ecc017",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":60,
              "y":261},
            "size":{
              "width":50,
              "height":44},
            "borderWidth":"1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "cornerRadiusTopLeft":"71"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"338acaf0a25f4839b8e23f349197a51e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":60,
                  "y":261},
                "size":{
                  "width":50,
                  "height":44},
                "borderWidth":"1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "cornerRadiusTopLeft":"71"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/优惠券/u47.png"}},
{
          "id":"88312cee3c5d496b80e38f1a0b0680d4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"700",
            "location":{
              "x":123,
              "y":252},
            "size":{
              "width":93,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"30036b33cbec4e0ab3569939cedb6288",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"700",
                "location":{
                  "x":123,
                  "y":252},
                "size":{
                  "width":93,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 优惠券详情",
                      "target":{
                        "targetType":"page",
                        "url":"优惠券详情_1.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a6a325cd91e8404caf6d78695ab04fc7",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":289,
              "y":270},
            "size":{
              "width":33,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f448b8303b9c4f1b9fffea87566dd6c5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":289,
                  "y":270},
                "size":{
                  "width":33,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"23201687f5a14e04a0f41dd21e8d30fb",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":261,
              "y":258},
            "size":{
              "width":10,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/优惠券/u53_line.png"}},
{
          "id":"26382fb676764c659d9d8af466fb9d33",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":123,
              "y":277},
            "size":{
              "width":59,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f7392950dbf842e2a606a8cdf99d057c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":123,
                  "y":277},
                "size":{
                  "width":59,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
    "0b7481d9291846af9389708a818f6ee6":{
      "packageId":"0b7481d9291846af9389708a818f6ee6",
      "type":"Axure:Master",
      "name":"手机",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"f1dfbdea093d41b09735aae262127399",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "size":{
                "width":388,
                "height":720},
              "borderWidth":"3",
              "borderFill":{
                "fillType":"solid",
                "color":0xFFCCCCCC},
              "cornerRadiusTopLeft":"23"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"54ce0076fc284f268413b560877042f3",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":388,
                    "height":720},
                  "borderWidth":"3",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFCCCCCC},
                  "cornerRadiusTopLeft":"23"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/登录/u1.png"}},
{
            "id":"ab9e31cf23e142ee94d04b46c74b970e",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFFF2F2F2},
              "location":{
                "x":36,
                "y":91},
              "size":{
                "width":320,
                "height":480},
              "borderWidth":"-1",
              "borderFill":{
                "fillType":"solid",
                "color":0xFFFFFF}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"3ab26a5565ea402f9f26e370e766ab77",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFF2F2F2},
                  "location":{
                    "x":36,
                    "y":91},
                  "size":{
                    "width":320,
                    "height":480},
                  "borderWidth":"-1",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFFFFF}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/登录/u3.png"}},
{
            "id":"778d1d4e585c4b1999a8a13f41c86394",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFF333333},
              "location":{
                "x":36,
                "y":91},
              "size":{
                "width":320,
                "height":20},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFFFFF}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"6393b6169e4944b0a5bacb6e7876f663",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF333333},
                  "location":{
                    "x":36,
                    "y":91},
                  "size":{
                    "width":320,
                    "height":20},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFFFFF}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/登录/u5.png"}},
{
            "id":"82466aad239343fd99ca0aa832fce046",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFFF2F2F2},
              "location":{
                "x":159,
                "y":610},
              "size":{
                "width":60,
                "height":61},
              "borderWidth":"3",
              "borderFill":{
                "fillType":"solid",
                "color":0xFFCCCCCC},
              "cornerRadiusTopLeft":"100"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"449f01aeeeb24531a1c8210ccbb014cc",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFF2F2F2},
                  "location":{
                    "x":159,
                    "y":610},
                  "size":{
                    "width":60,
                    "height":61},
                  "borderWidth":"3",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFCCCCCC},
                  "cornerRadiusTopLeft":"100"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/登录/u7.png"}},
{
            "id":"3961b32dcc1a40fcbc6bfd22d98eeae2",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFF999999},
              "location":{
                "x":179,
                "y":631},
              "size":{
                "width":20,
                "height":20},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFFFFF},
              "cornerRadiusTopLeft":"4"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"7b559f9ed3de40848129dd2ad0bc1939",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF999999},
                  "location":{
                    "x":179,
                    "y":631},
                  "size":{
                    "width":20,
                    "height":20},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFFFFF},
                  "cornerRadiusTopLeft":"4"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/登录/u9.png"}},
{
            "id":"30ab91e377a6423ab81eff19444f2d2a",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"12px",
              "horizontalAlignment":"center",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "location":{
                "x":164,
                "y":94},
              "size":{
                "width":75,
                "height":15},
              "rotation":"0",
              "textRotation":"0"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"b41c87afa21f477ea7270b37c48e7eff",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"12px",
                  "horizontalAlignment":"center",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "location":{
                    "x":164,
                    "y":94},
                  "size":{
                    "width":75,
                    "height":15},
                  "rotation":"0",
                  "textRotation":"0"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"af1cf1fd332945d298cfea08298ec3ea",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":323,
                "y":95},
              "size":{
                "width":22,
                "height":11},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFFFFF}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"a2ce34bd582a4f0d973a5b715165689d",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":323,
                    "y":95},
                  "size":{
                    "width":22,
                    "height":11},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFFFFF}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/登录/u13.png"}},
{
            "id":"1b60a919ae904b59919e6507de351e77",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":345,
                "y":98},
              "size":{
                "width":4,
                "height":5},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFFFFF},
              "cornerRadiusTopLeft":"1"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"94059979496c45349791a403f98024ed",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":345,
                    "y":98},
                  "size":{
                    "width":4,
                    "height":5},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFFFFF},
                  "cornerRadiusTopLeft":"1"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/登录/u15.png"}},
{
            "id":"25da23a08fcb444cbbf1fc72394fd476",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"11px",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "location":{
                "x":43,
                "y":94},
              "size":{
                "width":82,
                "height":14},
              "rotation":"0",
              "textRotation":"0"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"b78d3bea065748e6888c0f75e83057ed",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"11px",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "location":{
                    "x":43,
                    "y":94},
                  "size":{
                    "width":82,
                    "height":14},
                  "rotation":"0",
                  "textRotation":"0"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"8b2e58b05d324d178a80af84d5a955a9",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFF999999},
              "location":{
                "x":174,
                "y":64},
              "size":{
                "width":50,
                "height":8},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFFFFF},
              "cornerRadiusTopLeft":"6"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"cfe4a760e0c9478db90a300bb7258014",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF999999},
                  "location":{
                    "x":174,
                    "y":64},
                  "size":{
                    "width":50,
                    "height":8},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFFFFF},
                  "cornerRadiusTopLeft":"6"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/登录/u19.png"}},
{
            "id":"598708d1af384602b9a84271fd9fb443",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFF999999},
              "location":{
                "x":195,
                "y":50},
              "size":{
                "width":10,
                "height":10},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFFFFF},
              "cornerRadiusTopLeft":"8"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"bcd9c014b42141d2991ecfeecdfa8069",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF999999},
                  "location":{
                    "x":195,
                    "y":50},
                  "size":{
                    "width":10,
                    "height":10},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFFFFF},
                  "cornerRadiusTopLeft":"8"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/登录/u21.png"}}]}}},
  "objectPaths":{
    "b3b270ce980d4a5db65c5a42205fb823":{
      "scriptId":"u0",
      "f1dfbdea093d41b09735aae262127399":{
        "scriptId":"u1"},
      "54ce0076fc284f268413b560877042f3":{
        "scriptId":"u2"},
      "ab9e31cf23e142ee94d04b46c74b970e":{
        "scriptId":"u3"},
      "3ab26a5565ea402f9f26e370e766ab77":{
        "scriptId":"u4"},
      "778d1d4e585c4b1999a8a13f41c86394":{
        "scriptId":"u5"},
      "6393b6169e4944b0a5bacb6e7876f663":{
        "scriptId":"u6"},
      "82466aad239343fd99ca0aa832fce046":{
        "scriptId":"u7"},
      "449f01aeeeb24531a1c8210ccbb014cc":{
        "scriptId":"u8"},
      "3961b32dcc1a40fcbc6bfd22d98eeae2":{
        "scriptId":"u9"},
      "7b559f9ed3de40848129dd2ad0bc1939":{
        "scriptId":"u10"},
      "30ab91e377a6423ab81eff19444f2d2a":{
        "scriptId":"u11"},
      "b41c87afa21f477ea7270b37c48e7eff":{
        "scriptId":"u12"},
      "af1cf1fd332945d298cfea08298ec3ea":{
        "scriptId":"u13"},
      "a2ce34bd582a4f0d973a5b715165689d":{
        "scriptId":"u14"},
      "1b60a919ae904b59919e6507de351e77":{
        "scriptId":"u15"},
      "94059979496c45349791a403f98024ed":{
        "scriptId":"u16"},
      "25da23a08fcb444cbbf1fc72394fd476":{
        "scriptId":"u17"},
      "b78d3bea065748e6888c0f75e83057ed":{
        "scriptId":"u18"},
      "8b2e58b05d324d178a80af84d5a955a9":{
        "scriptId":"u19"},
      "cfe4a760e0c9478db90a300bb7258014":{
        "scriptId":"u20"},
      "598708d1af384602b9a84271fd9fb443":{
        "scriptId":"u21"},
      "bcd9c014b42141d2991ecfeecdfa8069":{
        "scriptId":"u22"}},
    "f127333ab6a04bc6858ad4e5b8c4bc6c":{
      "scriptId":"u23"},
    "38a13410c60a4ba3b6489b3061d2939e":{
      "scriptId":"u24"},
    "afdd9cf122b6459c9cb9f57de50d3f13":{
      "scriptId":"u25"},
    "6a450eecfba84edbb71966a277b5f9a0":{
      "scriptId":"u26"},
    "4c4e13f5128d4234b439b27c4ddd241a":{
      "scriptId":"u27"},
    "94984e12485f4158a6c9be81858bc5ab":{
      "scriptId":"u28"},
    "a67e66872150435ab354e126f91aaaf0":{
      "scriptId":"u29"},
    "9fa1b4e27b974c7f8960d07f53b9c4e7":{
      "scriptId":"u30"},
    "4d539fb245df49bcb52ceb389b915e3f":{
      "scriptId":"u31"},
    "dca5fe91d99c41baaf3dd1304fdc8275":{
      "scriptId":"u32"},
    "c1dfb64f0c30457ea1a1fc84c19066ee":{
      "scriptId":"u33"},
    "a4ba53a9b4e14fa8be39a0bb5a4c573c":{
      "scriptId":"u34"},
    "50dc5e45acaa435fb726cd178daa82b5":{
      "scriptId":"u35"},
    "0576fcc5f7514b73849a5cd9df63a759":{
      "scriptId":"u36"},
    "abf54b06f94e4a92a1d60ac3fbffdfbc":{
      "scriptId":"u37"},
    "7685fae8b23647109bec2d0a5a5bb2f8":{
      "scriptId":"u38"},
    "86ea8324eaba4e86b3bbd76bdb262d9e":{
      "scriptId":"u39"},
    "1c3fb17113f14ddea13ffe4f9eaaf045":{
      "scriptId":"u40"},
    "441a577d62b64fcdb65ee1c68a5f3219":{
      "scriptId":"u41"},
    "4a3fb40b368241e39258c50f844313eb":{
      "scriptId":"u42"},
    "82b1202be2cd4e04af619dbfc747cafa":{
      "scriptId":"u43"},
    "a7e37d1ed2c5432999fe4772f41b8048":{
      "scriptId":"u44"},
    "c8a7b6e1738c4988bcb541f0eed5c0f5":{
      "scriptId":"u45"},
    "6904f36601f84db288c0b21fe2800e75":{
      "scriptId":"u46"},
    "d3c0481c1636492fae9d4bff13579915":{
      "scriptId":"u47"},
    "6ebbb1596df44819b1d3c8553b89ea79":{
      "scriptId":"u48"},
    "4cbfe69335af4b769cc53308476e2006":{
      "scriptId":"u49"},
    "15681647c78041a49f7df225d4720551":{
      "scriptId":"u50"},
    "ade5b2dfe1624460a8a100630c63d37f":{
      "scriptId":"u51"},
    "b6e046a088ae43b09a4080afe6249ec3":{
      "scriptId":"u52"},
    "056e789f96704061926d58a233512a49":{
      "scriptId":"u53"},
    "66fe7e3301e14b24a1ab71e3358fb54a":{
      "scriptId":"u54"},
    "9bb85b1b17f54153a1cee4134503bf81":{
      "scriptId":"u55"},
    "cbf9fdba8061481ca15123934645e024":{
      "scriptId":"u56"},
    "fdd9845d123c472c8793f0bcc2ecc017":{
      "scriptId":"u57"},
    "338acaf0a25f4839b8e23f349197a51e":{
      "scriptId":"u58"},
    "88312cee3c5d496b80e38f1a0b0680d4":{
      "scriptId":"u59"},
    "30036b33cbec4e0ab3569939cedb6288":{
      "scriptId":"u60"},
    "a6a325cd91e8404caf6d78695ab04fc7":{
      "scriptId":"u61"},
    "f448b8303b9c4f1b9fffea87566dd6c5":{
      "scriptId":"u62"},
    "23201687f5a14e04a0f41dd21e8d30fb":{
      "scriptId":"u63"},
    "26382fb676764c659d9d8af466fb9d33":{
      "scriptId":"u64"},
    "f7392950dbf842e2a606a8cdf99d057c":{
      "scriptId":"u65"}}});