$axure.loadCurrentPage({
  "url":"活动.html",
  "generationDate":new Date(1438070190622.97),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"3ba1068ab64e4f8c8d0056bb7188e3dc",
    "type":"Axure:Page",
    "name":"活动",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"49a3755d60604a539e6475d24431b29b",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"0b7481d9291846af9389708a818f6ee6"},
{
          "id":"29be24de94ab45079e5933c1914fea9e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":36,
              "y":109},
            "size":{
              "width":320,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b9bb33ee5e8345269e45cdfbd9bf4681",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":36,
                  "y":109},
                "size":{
                  "width":320,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注册/u23.png"}},
{
          "id":"e6cd2b392c344f959c09b85dfd5c51bd",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":46,
              "y":330},
            "size":{
              "width":197,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"393a569e9bdd4ed9b6251aab9dd98211",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":46,
                  "y":330},
                "size":{
                  "width":197,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 活动详情",
                      "target":{
                        "targetType":"page",
                        "url":"活动详情.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5cdef18636c04f75b15f68a0dcaa4022",
          "label":"",
          "type":"menuObject",
          "styleType":"menuObject",
          "visible":true,
          "style":{
            "location":{
              "x":36,
              "y":148},
            "size":{
              "width":320,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"65f7b8941e7d479685f1bb2bef27aa31",
              "label":"",
              "type":"table",
              "styleType":"table",
              "visible":true,
              "style":{
                "size":{
                  "width":320,
                  "height":40}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"95b9d6af00584bbc83f209924e52f0b3",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "fontSize":"14px",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0x4CF2F2F2},
                    "location":{
                      "x":161,
                      "y":0},
                    "size":{
                      "width":159,
                      "height":40},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFF2F2F2}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"12ae96c184dc40cc82d08ecbd443c2dd",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0x4CF2F2F2},
                        "location":{
                          "x":161,
                          "y":0},
                        "size":{
                          "width":159,
                          "height":40},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFF2F2F2}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/活动/u31.png"}},
{
                  "id":"8645d4f2c18f43089146dd2e768f2b82",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "fontSize":"14px",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0x4CF2F2F2},
                    "size":{
                      "width":161,
                      "height":40},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFF2F2F2}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"bc6675becf5242e59dd5352347f7f6a6",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0x4CF2F2F2},
                        "size":{
                          "width":161,
                          "height":40},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFF2F2F2}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/活动/u29.png"}}]}]},
{
          "id":"6703003e638f40c2be118dc19cd43f1f",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":36,
              "y":183},
            "size":{
              "width":163,
              "height":10},
            "borderWidth":"2"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/活动/u33_line.png"}},
{
          "id":"dfac779c2ab2489fb6c22727f379bb8e",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":36,
              "y":520}},
          "adaptiveStyles":{
},
          "masterId":"fdbf0fa723dd4210bf40f97a1db88128"},
{
          "id":"25c6221a157749479c9d44785c15aa30",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":46,
              "y":203},
            "size":{
              "width":294,
              "height":121}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d64e40b14a874504a2241e37875c9a46",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":46,
                  "y":203},
                "size":{
                  "width":294,
                  "height":121}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 活动详情",
                      "target":{
                        "targetType":"page",
                        "url":"活动详情.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/活动/u45.jpg"}},
{
          "id":"596652362c124b95b52037525945db66",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":46,
              "y":491},
            "size":{
              "width":197,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b02e56a856524286bf6cc07a658069ff",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":46,
                  "y":491},
                "size":{
                  "width":197,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 活动详情",
                      "target":{
                        "targetType":"page",
                        "url":"活动详情.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9b7b93e6218d472ab26684fb9395855d",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":46,
              "y":359},
            "size":{
              "width":294,
              "height":121}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a5c58790417c49d7be57d24e3b1047ea",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":46,
                  "y":359},
                "size":{
                  "width":294,
                  "height":121}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 活动详情",
                      "target":{
                        "targetType":"page",
                        "url":"活动详情.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/活动/u49.jpg"}}]}},
  "masters":{
    "0b7481d9291846af9389708a818f6ee6":{
      "packageId":"0b7481d9291846af9389708a818f6ee6",
      "type":"Axure:Master",
      "name":"手机",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"f1dfbdea093d41b09735aae262127399",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "size":{
                "width":388,
                "height":720},
              "borderWidth":"3",
              "borderFill":{
                "fillType":"solid",
                "color":0xFFCCCCCC},
              "cornerRadiusTopLeft":"23"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"54ce0076fc284f268413b560877042f3",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":388,
                    "height":720},
                  "borderWidth":"3",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFCCCCCC},
                  "cornerRadiusTopLeft":"23"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/登录/u1.png"}},
{
            "id":"ab9e31cf23e142ee94d04b46c74b970e",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFFF2F2F2},
              "location":{
                "x":36,
                "y":91},
              "size":{
                "width":320,
                "height":480},
              "borderWidth":"-1",
              "borderFill":{
                "fillType":"solid",
                "color":0xFFFFFF}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"3ab26a5565ea402f9f26e370e766ab77",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFF2F2F2},
                  "location":{
                    "x":36,
                    "y":91},
                  "size":{
                    "width":320,
                    "height":480},
                  "borderWidth":"-1",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFFFFF}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/登录/u3.png"}},
{
            "id":"778d1d4e585c4b1999a8a13f41c86394",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFF333333},
              "location":{
                "x":36,
                "y":91},
              "size":{
                "width":320,
                "height":20},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFFFFF}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"6393b6169e4944b0a5bacb6e7876f663",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF333333},
                  "location":{
                    "x":36,
                    "y":91},
                  "size":{
                    "width":320,
                    "height":20},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFFFFF}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/登录/u5.png"}},
{
            "id":"82466aad239343fd99ca0aa832fce046",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFFF2F2F2},
              "location":{
                "x":159,
                "y":610},
              "size":{
                "width":60,
                "height":61},
              "borderWidth":"3",
              "borderFill":{
                "fillType":"solid",
                "color":0xFFCCCCCC},
              "cornerRadiusTopLeft":"100"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"449f01aeeeb24531a1c8210ccbb014cc",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFF2F2F2},
                  "location":{
                    "x":159,
                    "y":610},
                  "size":{
                    "width":60,
                    "height":61},
                  "borderWidth":"3",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFCCCCCC},
                  "cornerRadiusTopLeft":"100"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/登录/u7.png"}},
{
            "id":"3961b32dcc1a40fcbc6bfd22d98eeae2",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFF999999},
              "location":{
                "x":179,
                "y":631},
              "size":{
                "width":20,
                "height":20},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFFFFF},
              "cornerRadiusTopLeft":"4"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"7b559f9ed3de40848129dd2ad0bc1939",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF999999},
                  "location":{
                    "x":179,
                    "y":631},
                  "size":{
                    "width":20,
                    "height":20},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFFFFF},
                  "cornerRadiusTopLeft":"4"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/登录/u9.png"}},
{
            "id":"30ab91e377a6423ab81eff19444f2d2a",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"12px",
              "horizontalAlignment":"center",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "location":{
                "x":164,
                "y":94},
              "size":{
                "width":75,
                "height":15},
              "rotation":"0",
              "textRotation":"0"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"b41c87afa21f477ea7270b37c48e7eff",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"12px",
                  "horizontalAlignment":"center",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "location":{
                    "x":164,
                    "y":94},
                  "size":{
                    "width":75,
                    "height":15},
                  "rotation":"0",
                  "textRotation":"0"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"af1cf1fd332945d298cfea08298ec3ea",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":323,
                "y":95},
              "size":{
                "width":22,
                "height":11},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFFFFF}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"a2ce34bd582a4f0d973a5b715165689d",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":323,
                    "y":95},
                  "size":{
                    "width":22,
                    "height":11},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFFFFF}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/登录/u13.png"}},
{
            "id":"1b60a919ae904b59919e6507de351e77",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":345,
                "y":98},
              "size":{
                "width":4,
                "height":5},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFFFFF},
              "cornerRadiusTopLeft":"1"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"94059979496c45349791a403f98024ed",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":345,
                    "y":98},
                  "size":{
                    "width":4,
                    "height":5},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFFFFF},
                  "cornerRadiusTopLeft":"1"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/登录/u15.png"}},
{
            "id":"25da23a08fcb444cbbf1fc72394fd476",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"11px",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "location":{
                "x":43,
                "y":94},
              "size":{
                "width":82,
                "height":14},
              "rotation":"0",
              "textRotation":"0"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"b78d3bea065748e6888c0f75e83057ed",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"11px",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "location":{
                    "x":43,
                    "y":94},
                  "size":{
                    "width":82,
                    "height":14},
                  "rotation":"0",
                  "textRotation":"0"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"8b2e58b05d324d178a80af84d5a955a9",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFF999999},
              "location":{
                "x":174,
                "y":64},
              "size":{
                "width":50,
                "height":8},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFFFFF},
              "cornerRadiusTopLeft":"6"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"cfe4a760e0c9478db90a300bb7258014",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF999999},
                  "location":{
                    "x":174,
                    "y":64},
                  "size":{
                    "width":50,
                    "height":8},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFFFFF},
                  "cornerRadiusTopLeft":"6"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/登录/u19.png"}},
{
            "id":"598708d1af384602b9a84271fd9fb443",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFF999999},
              "location":{
                "x":195,
                "y":50},
              "size":{
                "width":10,
                "height":10},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFFFFF},
              "cornerRadiusTopLeft":"8"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"bcd9c014b42141d2991ecfeecdfa8069",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF999999},
                  "location":{
                    "x":195,
                    "y":50},
                  "size":{
                    "width":10,
                    "height":10},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFFFFF},
                  "cornerRadiusTopLeft":"8"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/登录/u21.png"}}]}},
    "fdbf0fa723dd4210bf40f97a1db88128":{
      "packageId":"fdbf0fa723dd4210bf40f97a1db88128",
      "type":"Axure:Master",
      "name":"新母版 3",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"f04e46641eb84435bb35e3e03b9acc2d",
            "label":"",
            "type":"menuObject",
            "styleType":"menuObject",
            "visible":true,
            "style":{
              "size":{
                "width":320,
                "height":50}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"e56d860593fb4430b55663ef0bcabf6b",
                "label":"",
                "type":"table",
                "styleType":"table",
                "visible":true,
                "style":{
                  "size":{
                    "width":320,
                    "height":50}},
                "adaptiveStyles":{
},
                "objects":[{
                    "id":"2c2e98c2e7f048d682c1dc35b032b81f",
                    "label":"商圈",
                    "type":"tableCell",
                    "styleType":"tableCell",
                    "visible":true,
                    "style":{
                      "fontName":"'Arial Negreta', 'Arial'",
                      "fontSize":"14px",
                      "fontWeight":"700",
                      "horizontalAlignment":"center",
                      "verticalAlignment":"middle",
                      "stateStyles":{
                        "mouseOver":{
                          "fill":{
                            "fillType":"solid",
                            "color":0xFFE4E4E4}},
                        "selected":{
                          "foreGroundFill":{
                            "fillType":"solid",
                            "color":0xFFFFFFFF,
                            "opacity":1},
                          "fill":{
                            "fillType":"solid",
                            "color":0xFF333333}}},
                      "size":{
                        "width":80,
                        "height":50},
                      "borderFill":{
                        "fillType":"solid",
                        "color":0xFFCCCCCC}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"c27e9967de0e4a559e8a6123d42973c5",
                        "label":"",
                        "isContained":true,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontName":"'Arial Negreta', 'Arial'",
                          "fontSize":"14px",
                          "fontWeight":"700",
                          "horizontalAlignment":"center",
                          "verticalAlignment":"middle",
                          "stateStyles":{
                            "mouseOver":{
                              "fill":{
                                "fillType":"solid",
                                "color":0xFFE4E4E4}},
                            "selected":{
                              "foreGroundFill":{
                                "fillType":"solid",
                                "color":0xFFFFFFFF,
                                "opacity":1},
                              "fill":{
                                "fillType":"solid",
                                "color":0xFF333333}}},
                          "size":{
                            "width":80,
                            "height":50},
                          "borderFill":{
                            "fillType":"solid",
                            "color":0xFFCCCCCC}},
                        "adaptiveStyles":{
}}],
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"用例 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"在 当前窗口 打开 优惠券",
                                "target":{
                                  "targetType":"page",
                                  "url":"优惠券.html",
                                  "includeVariables":true},
                                "linkType":"current"}]}]}},
                    "tabbable":true,
                    "images":{
                      "normal~":"images/优惠券/商圈_u28.png",
                      "selected~":"images/优惠券/商圈_u28_selected.png",
                      "mouseOver~":"images/优惠券/商圈_u28_mouseOver.png"}},
{
                    "id":"938e17154fbf410aad672ad1edada5b4",
                    "label":"活动",
                    "type":"tableCell",
                    "styleType":"tableCell",
                    "visible":true,
                    "style":{
                      "fontName":"'Arial Negreta', 'Arial'",
                      "fontSize":"14px",
                      "fontWeight":"700",
                      "horizontalAlignment":"center",
                      "verticalAlignment":"middle",
                      "stateStyles":{
                        "mouseOver":{
                          "fill":{
                            "fillType":"solid",
                            "color":0xFFE4E4E4}},
                        "selected":{
                          "foreGroundFill":{
                            "fillType":"solid",
                            "color":0xFFFFFFFF,
                            "opacity":1},
                          "fill":{
                            "fillType":"solid",
                            "color":0xFF333333}}},
                      "fill":{
                        "fillType":"solid",
                        "color":0xFFFFFF},
                      "location":{
                        "x":160,
                        "y":0},
                      "size":{
                        "width":80,
                        "height":50},
                      "borderFill":{
                        "fillType":"solid",
                        "color":0xFFCCCCCC}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"6ab6720582194ad297290f9aacbb77c8",
                        "label":"",
                        "isContained":true,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontName":"'Arial Negreta', 'Arial'",
                          "fontSize":"14px",
                          "fontWeight":"700",
                          "horizontalAlignment":"center",
                          "verticalAlignment":"middle",
                          "stateStyles":{
                            "mouseOver":{
                              "fill":{
                                "fillType":"solid",
                                "color":0xFFE4E4E4}},
                            "selected":{
                              "foreGroundFill":{
                                "fillType":"solid",
                                "color":0xFFFFFFFF,
                                "opacity":1},
                              "fill":{
                                "fillType":"solid",
                                "color":0xFF333333}}},
                          "fill":{
                            "fillType":"solid",
                            "color":0xFFFFFF},
                          "location":{
                            "x":160,
                            "y":0},
                          "size":{
                            "width":80,
                            "height":50},
                          "borderFill":{
                            "fillType":"solid",
                            "color":0xFFCCCCCC}},
                        "adaptiveStyles":{
}}],
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"用例 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"在 当前窗口 打开 链接",
                                "target":{
                                  "targetType":"page",
                                  "includeVariables":true},
                                "linkType":"current"}]}]}},
                    "tabbable":true,
                    "images":{
                      "normal~":"images/优惠券/抽奖_u30.png",
                      "selected~":"images/优惠券/商圈_u28_selected.png",
                      "mouseOver~":"images/优惠券/商圈_u28_mouseOver.png"}},
{
                    "id":"13939581c1e1494fbf2606e44be268b4",
                    "label":"我",
                    "type":"tableCell",
                    "styleType":"tableCell",
                    "visible":true,
                    "style":{
                      "fontName":"'Arial Negreta', 'Arial'",
                      "fontSize":"14px",
                      "fontWeight":"700",
                      "horizontalAlignment":"center",
                      "verticalAlignment":"middle",
                      "stateStyles":{
                        "mouseOver":{
                          "fill":{
                            "fillType":"solid",
                            "color":0xFFE4E4E4}},
                        "selected":{
                          "foreGroundFill":{
                            "fillType":"solid",
                            "color":0xFFFFFFFF,
                            "opacity":1},
                          "fill":{
                            "fillType":"solid",
                            "color":0xFF333333}}},
                      "fill":{
                        "fillType":"solid",
                        "color":0xFFFFFF},
                      "location":{
                        "x":240,
                        "y":0},
                      "size":{
                        "width":80,
                        "height":50},
                      "borderFill":{
                        "fillType":"solid",
                        "color":0xFFCCCCCC}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"c28454dab52b41a58a0c9cb4c3039e2a",
                        "label":"",
                        "isContained":true,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontName":"'Arial Negreta', 'Arial'",
                          "fontSize":"14px",
                          "fontWeight":"700",
                          "horizontalAlignment":"center",
                          "verticalAlignment":"middle",
                          "stateStyles":{
                            "mouseOver":{
                              "fill":{
                                "fillType":"solid",
                                "color":0xFFE4E4E4}},
                            "selected":{
                              "foreGroundFill":{
                                "fillType":"solid",
                                "color":0xFFFFFFFF,
                                "opacity":1},
                              "fill":{
                                "fillType":"solid",
                                "color":0xFF333333}}},
                          "fill":{
                            "fillType":"solid",
                            "color":0xFFFFFF},
                          "location":{
                            "x":240,
                            "y":0},
                          "size":{
                            "width":80,
                            "height":50},
                          "borderFill":{
                            "fillType":"solid",
                            "color":0xFFCCCCCC}},
                        "adaptiveStyles":{
}}],
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"用例 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"在 当前窗口 打开 我",
                                "target":{
                                  "targetType":"page",
                                  "url":"我.html",
                                  "includeVariables":true},
                                "linkType":"current"}]}]}},
                    "tabbable":true,
                    "images":{
                      "normal~":"images/优惠券/我_u34.png",
                      "selected~":"images/优惠券/我_u34_selected.png",
                      "mouseOver~":"images/优惠券/我_u34_mouseOver.png"}},
{
                    "id":"9ce6a9bbecce41ef95d8e8846eb6a0a1",
                    "label":"抽奖",
                    "type":"tableCell",
                    "styleType":"tableCell",
                    "visible":true,
                    "style":{
                      "fontName":"'Arial Negreta', 'Arial'",
                      "fontSize":"14px",
                      "fontWeight":"700",
                      "horizontalAlignment":"center",
                      "verticalAlignment":"middle",
                      "stateStyles":{
                        "mouseOver":{
                          "fill":{
                            "fillType":"solid",
                            "color":0xFFE4E4E4}},
                        "selected":{
                          "foreGroundFill":{
                            "fillType":"solid",
                            "color":0xFFFFFFFF,
                            "opacity":1},
                          "fill":{
                            "fillType":"solid",
                            "color":0xFF333333}}},
                      "fill":{
                        "fillType":"solid",
                        "color":0xFFFFFF},
                      "location":{
                        "x":80,
                        "y":0},
                      "size":{
                        "width":80,
                        "height":50},
                      "borderFill":{
                        "fillType":"solid",
                        "color":0xFFCCCCCC}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"0fd61227d96a45829fb37ca41b572377",
                        "label":"",
                        "isContained":true,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontName":"'Arial Negreta', 'Arial'",
                          "fontSize":"14px",
                          "fontWeight":"700",
                          "horizontalAlignment":"center",
                          "verticalAlignment":"middle",
                          "stateStyles":{
                            "mouseOver":{
                              "fill":{
                                "fillType":"solid",
                                "color":0xFFE4E4E4}},
                            "selected":{
                              "foreGroundFill":{
                                "fillType":"solid",
                                "color":0xFFFFFFFF,
                                "opacity":1},
                              "fill":{
                                "fillType":"solid",
                                "color":0xFF333333}}},
                          "fill":{
                            "fillType":"solid",
                            "color":0xFFFFFF},
                          "location":{
                            "x":80,
                            "y":0},
                          "size":{
                            "width":80,
                            "height":50},
                          "borderFill":{
                            "fillType":"solid",
                            "color":0xFFCCCCCC}},
                        "adaptiveStyles":{
}}],
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"用例 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"在 当前窗口 打开 活动",
                                "target":{
                                  "targetType":"page",
                                  "url":"活动.html",
                                  "includeVariables":true},
                                "linkType":"current"}]}]}},
                    "tabbable":true,
                    "images":{
                      "normal~":"images/优惠券/抽奖_u30.png",
                      "selected~":"images/优惠券/商圈_u28_selected.png",
                      "mouseOver~":"images/优惠券/商圈_u28_mouseOver.png"}}]}]}]}}},
  "objectPaths":{
    "49a3755d60604a539e6475d24431b29b":{
      "scriptId":"u0",
      "f1dfbdea093d41b09735aae262127399":{
        "scriptId":"u1"},
      "54ce0076fc284f268413b560877042f3":{
        "scriptId":"u2"},
      "ab9e31cf23e142ee94d04b46c74b970e":{
        "scriptId":"u3"},
      "3ab26a5565ea402f9f26e370e766ab77":{
        "scriptId":"u4"},
      "778d1d4e585c4b1999a8a13f41c86394":{
        "scriptId":"u5"},
      "6393b6169e4944b0a5bacb6e7876f663":{
        "scriptId":"u6"},
      "82466aad239343fd99ca0aa832fce046":{
        "scriptId":"u7"},
      "449f01aeeeb24531a1c8210ccbb014cc":{
        "scriptId":"u8"},
      "3961b32dcc1a40fcbc6bfd22d98eeae2":{
        "scriptId":"u9"},
      "7b559f9ed3de40848129dd2ad0bc1939":{
        "scriptId":"u10"},
      "30ab91e377a6423ab81eff19444f2d2a":{
        "scriptId":"u11"},
      "b41c87afa21f477ea7270b37c48e7eff":{
        "scriptId":"u12"},
      "af1cf1fd332945d298cfea08298ec3ea":{
        "scriptId":"u13"},
      "a2ce34bd582a4f0d973a5b715165689d":{
        "scriptId":"u14"},
      "1b60a919ae904b59919e6507de351e77":{
        "scriptId":"u15"},
      "94059979496c45349791a403f98024ed":{
        "scriptId":"u16"},
      "25da23a08fcb444cbbf1fc72394fd476":{
        "scriptId":"u17"},
      "b78d3bea065748e6888c0f75e83057ed":{
        "scriptId":"u18"},
      "8b2e58b05d324d178a80af84d5a955a9":{
        "scriptId":"u19"},
      "cfe4a760e0c9478db90a300bb7258014":{
        "scriptId":"u20"},
      "598708d1af384602b9a84271fd9fb443":{
        "scriptId":"u21"},
      "bcd9c014b42141d2991ecfeecdfa8069":{
        "scriptId":"u22"}},
    "29be24de94ab45079e5933c1914fea9e":{
      "scriptId":"u23"},
    "b9bb33ee5e8345269e45cdfbd9bf4681":{
      "scriptId":"u24"},
    "e6cd2b392c344f959c09b85dfd5c51bd":{
      "scriptId":"u25"},
    "393a569e9bdd4ed9b6251aab9dd98211":{
      "scriptId":"u26"},
    "5cdef18636c04f75b15f68a0dcaa4022":{
      "scriptId":"u27"},
    "65f7b8941e7d479685f1bb2bef27aa31":{
      "scriptId":"u28"},
    "8645d4f2c18f43089146dd2e768f2b82":{
      "scriptId":"u29"},
    "bc6675becf5242e59dd5352347f7f6a6":{
      "scriptId":"u30"},
    "95b9d6af00584bbc83f209924e52f0b3":{
      "scriptId":"u31"},
    "12ae96c184dc40cc82d08ecbd443c2dd":{
      "scriptId":"u32"},
    "6703003e638f40c2be118dc19cd43f1f":{
      "scriptId":"u33"},
    "dfac779c2ab2489fb6c22727f379bb8e":{
      "scriptId":"u34",
      "f04e46641eb84435bb35e3e03b9acc2d":{
        "scriptId":"u35"},
      "e56d860593fb4430b55663ef0bcabf6b":{
        "scriptId":"u36"},
      "2c2e98c2e7f048d682c1dc35b032b81f":{
        "scriptId":"u37"},
      "c27e9967de0e4a559e8a6123d42973c5":{
        "scriptId":"u38"},
      "9ce6a9bbecce41ef95d8e8846eb6a0a1":{
        "scriptId":"u39"},
      "0fd61227d96a45829fb37ca41b572377":{
        "scriptId":"u40"},
      "938e17154fbf410aad672ad1edada5b4":{
        "scriptId":"u41"},
      "6ab6720582194ad297290f9aacbb77c8":{
        "scriptId":"u42"},
      "13939581c1e1494fbf2606e44be268b4":{
        "scriptId":"u43"},
      "c28454dab52b41a58a0c9cb4c3039e2a":{
        "scriptId":"u44"}},
    "25c6221a157749479c9d44785c15aa30":{
      "scriptId":"u45"},
    "d64e40b14a874504a2241e37875c9a46":{
      "scriptId":"u46"},
    "596652362c124b95b52037525945db66":{
      "scriptId":"u47"},
    "b02e56a856524286bf6cc07a658069ff":{
      "scriptId":"u48"},
    "9b7b93e6218d472ab26684fb9395855d":{
      "scriptId":"u49"},
    "a5c58790417c49d7be57d24e3b1047ea":{
      "scriptId":"u50"}}});