$axure.loadCurrentPage({
  "url":"意见反馈.html",
  "generationDate":new Date(1438070191977.04),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"64a2feb4c72142ed9da5d586920f9169",
    "type":"Axure:Page",
    "name":"意见反馈",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"bd33c89c1dfd410ba1733d4868c09998",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"0b7481d9291846af9389708a818f6ee6"},
{
          "id":"ed69a02766dd4f38855b8b5cdc0ed426",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":36,
              "y":109},
            "size":{
              "width":320,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"82857c01a865421e98b47bcc19f0ef15",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":36,
                  "y":109},
                "size":{
                  "width":320,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注册/u23.png"}},
{
          "id":"91abd424fece45e6b43b62bec14c48dd",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":47,
              "y":120},
            "size":{
              "width":18,
              "height":18},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cefd12d0786a47b2a599dfdb36a75475",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":47,
                  "y":120},
                "size":{
                  "width":18,
                  "height":18},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 系统设置",
                      "target":{
                        "targetType":"page",
                        "url":"系统设置.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/注册/u25.png"}},
{
          "id":"0ed0134f405b4894ae1bafaf1f94d224",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":36,
              "y":355}},
          "adaptiveStyles":{
},
          "masterId":"a02e172b7dc245d9a2d5da6c6f296692"},
{
          "id":"326e5ec0293e44cfbbefa58240ad139a",
          "label":"文本框",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":49,
              "y":165},
            "size":{
              "width":294,
              "height":25}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onFocus":{
              "description":"OnFocus",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"设置 文字于 文本框 等于 &quot;&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetWidgetFormText",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["326e5ec0293e44cfbbefa58240ad139a"]},
{
                                "exprType":"stringLiteral",
                                "value":"",
                                "stos":[]}]}]}}]}]},
            "onLostFocus":{
              "description":"OnLostFocus",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"设置 文字于 文本框 等于 &quot;您的意见是我们宝贵的财富&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetWidgetFormText",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["326e5ec0293e44cfbbefa58240ad139a"]},
{
                                "exprType":"stringLiteral",
                                "value":"您的意见是我们宝贵的财富",
                                "stos":[]}]}]}}]}]}},
          "tabbable":true},
{
          "id":"417394d173994b5683778a68e483d2ab",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF666666},
            "location":{
              "x":298,
              "y":114},
            "size":{
              "width":50,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a511d65a85284ff89a041700cfb03290",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF666666},
                "location":{
                  "x":298,
                  "y":114},
                "size":{
                  "width":50,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 系统设置",
                      "target":{
                        "targetType":"page",
                        "url":"系统设置.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/信息输入/u105.png"}}]}},
  "masters":{
    "0b7481d9291846af9389708a818f6ee6":{
      "packageId":"0b7481d9291846af9389708a818f6ee6",
      "type":"Axure:Master",
      "name":"手机",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"f1dfbdea093d41b09735aae262127399",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "size":{
                "width":388,
                "height":720},
              "borderWidth":"3",
              "borderFill":{
                "fillType":"solid",
                "color":0xFFCCCCCC},
              "cornerRadiusTopLeft":"23"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"54ce0076fc284f268413b560877042f3",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":388,
                    "height":720},
                  "borderWidth":"3",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFCCCCCC},
                  "cornerRadiusTopLeft":"23"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/登录/u1.png"}},
{
            "id":"ab9e31cf23e142ee94d04b46c74b970e",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFFF2F2F2},
              "location":{
                "x":36,
                "y":91},
              "size":{
                "width":320,
                "height":480},
              "borderWidth":"-1",
              "borderFill":{
                "fillType":"solid",
                "color":0xFFFFFF}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"3ab26a5565ea402f9f26e370e766ab77",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFF2F2F2},
                  "location":{
                    "x":36,
                    "y":91},
                  "size":{
                    "width":320,
                    "height":480},
                  "borderWidth":"-1",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFFFFF}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/登录/u3.png"}},
{
            "id":"778d1d4e585c4b1999a8a13f41c86394",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFF333333},
              "location":{
                "x":36,
                "y":91},
              "size":{
                "width":320,
                "height":20},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFFFFF}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"6393b6169e4944b0a5bacb6e7876f663",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF333333},
                  "location":{
                    "x":36,
                    "y":91},
                  "size":{
                    "width":320,
                    "height":20},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFFFFF}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/登录/u5.png"}},
{
            "id":"82466aad239343fd99ca0aa832fce046",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFFF2F2F2},
              "location":{
                "x":159,
                "y":610},
              "size":{
                "width":60,
                "height":61},
              "borderWidth":"3",
              "borderFill":{
                "fillType":"solid",
                "color":0xFFCCCCCC},
              "cornerRadiusTopLeft":"100"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"449f01aeeeb24531a1c8210ccbb014cc",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFF2F2F2},
                  "location":{
                    "x":159,
                    "y":610},
                  "size":{
                    "width":60,
                    "height":61},
                  "borderWidth":"3",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFCCCCCC},
                  "cornerRadiusTopLeft":"100"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/登录/u7.png"}},
{
            "id":"3961b32dcc1a40fcbc6bfd22d98eeae2",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFF999999},
              "location":{
                "x":179,
                "y":631},
              "size":{
                "width":20,
                "height":20},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFFFFF},
              "cornerRadiusTopLeft":"4"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"7b559f9ed3de40848129dd2ad0bc1939",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF999999},
                  "location":{
                    "x":179,
                    "y":631},
                  "size":{
                    "width":20,
                    "height":20},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFFFFF},
                  "cornerRadiusTopLeft":"4"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/登录/u9.png"}},
{
            "id":"30ab91e377a6423ab81eff19444f2d2a",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"12px",
              "horizontalAlignment":"center",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "location":{
                "x":164,
                "y":94},
              "size":{
                "width":75,
                "height":15},
              "rotation":"0",
              "textRotation":"0"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"b41c87afa21f477ea7270b37c48e7eff",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"12px",
                  "horizontalAlignment":"center",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "location":{
                    "x":164,
                    "y":94},
                  "size":{
                    "width":75,
                    "height":15},
                  "rotation":"0",
                  "textRotation":"0"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"af1cf1fd332945d298cfea08298ec3ea",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":323,
                "y":95},
              "size":{
                "width":22,
                "height":11},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFFFFF}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"a2ce34bd582a4f0d973a5b715165689d",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":323,
                    "y":95},
                  "size":{
                    "width":22,
                    "height":11},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFFFFF}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/登录/u13.png"}},
{
            "id":"1b60a919ae904b59919e6507de351e77",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":345,
                "y":98},
              "size":{
                "width":4,
                "height":5},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFFFFF},
              "cornerRadiusTopLeft":"1"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"94059979496c45349791a403f98024ed",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":345,
                    "y":98},
                  "size":{
                    "width":4,
                    "height":5},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFFFFF},
                  "cornerRadiusTopLeft":"1"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/登录/u15.png"}},
{
            "id":"25da23a08fcb444cbbf1fc72394fd476",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"11px",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "location":{
                "x":43,
                "y":94},
              "size":{
                "width":82,
                "height":14},
              "rotation":"0",
              "textRotation":"0"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"b78d3bea065748e6888c0f75e83057ed",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"11px",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "location":{
                    "x":43,
                    "y":94},
                  "size":{
                    "width":82,
                    "height":14},
                  "rotation":"0",
                  "textRotation":"0"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"8b2e58b05d324d178a80af84d5a955a9",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFF999999},
              "location":{
                "x":174,
                "y":64},
              "size":{
                "width":50,
                "height":8},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFFFFF},
              "cornerRadiusTopLeft":"6"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"cfe4a760e0c9478db90a300bb7258014",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF999999},
                  "location":{
                    "x":174,
                    "y":64},
                  "size":{
                    "width":50,
                    "height":8},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFFFFF},
                  "cornerRadiusTopLeft":"6"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/登录/u19.png"}},
{
            "id":"598708d1af384602b9a84271fd9fb443",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFF999999},
              "location":{
                "x":195,
                "y":50},
              "size":{
                "width":10,
                "height":10},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFFFFF},
              "cornerRadiusTopLeft":"8"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"bcd9c014b42141d2991ecfeecdfa8069",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF999999},
                  "location":{
                    "x":195,
                    "y":50},
                  "size":{
                    "width":10,
                    "height":10},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFFFFF},
                  "cornerRadiusTopLeft":"8"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/登录/u21.png"}}]}},
    "a02e172b7dc245d9a2d5da6c6f296692":{
      "packageId":"a02e172b7dc245d9a2d5da6c6f296692",
      "type":"Axure:Master",
      "name":"键盘",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"f6027dd3a01d4ddc8545ac0f83debaad",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontSize":"16px",
              "fill":{
                "fillType":"solid",
                "color":0xFF999999},
              "size":{
                "width":320,
                "height":215}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"f03764f9f19746bba494e147d06cd5b5",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"16px",
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF999999},
                  "size":{
                    "width":320,
                    "height":215}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/信息输入/u28.png"}},
{
            "id":"414006c5ba3d4647af3e881854e72aba",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontName":"'Myriad Bold', 'Myriad'",
              "fontSize":"16px",
              "fontWeight":"bold",
              "location":{
                "x":290,
                "y":11},
              "size":{
                "width":26,
                "height":39}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"d82e87bdb6884564b7c8bb363db169ed",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Myriad Bold', 'Myriad'",
                  "fontSize":"16px",
                  "fontWeight":"bold",
                  "location":{
                    "x":290,
                    "y":11},
                  "size":{
                    "width":26,
                    "height":39}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/信息输入/u30.png"}},
{
            "id":"e104c84544484dca9e86c052ec816f1e",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontName":"'Myriad Bold', 'Myriad'",
              "fontSize":"16px",
              "fontWeight":"bold",
              "location":{
                "x":260,
                "y":11},
              "size":{
                "width":26,
                "height":39}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"49873970094b4e27a96700f10c6d99ef",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Myriad Bold', 'Myriad'",
                  "fontSize":"16px",
                  "fontWeight":"bold",
                  "location":{
                    "x":260,
                    "y":11},
                  "size":{
                    "width":26,
                    "height":39}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/信息输入/u30.png"}},
{
            "id":"cf091cfbd4514a45b33a0e86dac8506b",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontName":"'Myriad Bold', 'Myriad'",
              "fontSize":"16px",
              "fontWeight":"bold",
              "location":{
                "x":4,
                "y":11},
              "size":{
                "width":26,
                "height":39}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"b101d1531c8b4db7afc485150efe0ef8",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Myriad Bold', 'Myriad'",
                  "fontSize":"16px",
                  "fontWeight":"bold",
                  "location":{
                    "x":4,
                    "y":11},
                  "size":{
                    "width":26,
                    "height":39}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/信息输入/u30.png"}},
{
            "id":"8ed3ca947c5b4bc895ea4e46dd4abe06",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontName":"'Myriad Bold', 'Myriad'",
              "fontSize":"16px",
              "fontWeight":"bold",
              "location":{
                "x":37,
                "y":11},
              "size":{
                "width":26,
                "height":39}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"84e244372d654c7fab63687cf8d4aced",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Myriad Bold', 'Myriad'",
                  "fontSize":"16px",
                  "fontWeight":"bold",
                  "location":{
                    "x":37,
                    "y":11},
                  "size":{
                    "width":26,
                    "height":39}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/信息输入/u30.png"}},
{
            "id":"348f01660f424b3f8cccc305115aa163",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontName":"'Myriad Bold', 'Myriad'",
              "fontSize":"16px",
              "fontWeight":"bold",
              "location":{
                "x":68,
                "y":11},
              "size":{
                "width":26,
                "height":39}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"667e5d772d2c4116b7b7c9abc5a3f498",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Myriad Bold', 'Myriad'",
                  "fontSize":"16px",
                  "fontWeight":"bold",
                  "location":{
                    "x":68,
                    "y":11},
                  "size":{
                    "width":26,
                    "height":39}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/信息输入/u30.png"}},
{
            "id":"e342fb61408d4c25ac931fbecd65b229",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontName":"'Myriad Bold', 'Myriad'",
              "fontSize":"16px",
              "fontWeight":"bold",
              "location":{
                "x":98,
                "y":11},
              "size":{
                "width":27,
                "height":39}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"d441b832bb4c422a8b541f79064f5419",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Myriad Bold', 'Myriad'",
                  "fontSize":"16px",
                  "fontWeight":"bold",
                  "location":{
                    "x":98,
                    "y":11},
                  "size":{
                    "width":27,
                    "height":39}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/信息输入/u40.png"}},
{
            "id":"d7b3afa2886547b7b2628ba9314eac1b",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontName":"'Myriad Bold', 'Myriad'",
              "fontSize":"16px",
              "fontWeight":"bold",
              "location":{
                "x":130,
                "y":11},
              "size":{
                "width":27,
                "height":39}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"ba4669520afc4a2caf201d63d4676a65",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Myriad Bold', 'Myriad'",
                  "fontSize":"16px",
                  "fontWeight":"bold",
                  "location":{
                    "x":130,
                    "y":11},
                  "size":{
                    "width":27,
                    "height":39}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/信息输入/u40.png"}},
{
            "id":"a1d72e34fb0e4f82bc81a4b77958f5ad",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontName":"'Myriad Bold', 'Myriad'",
              "fontSize":"16px",
              "fontWeight":"bold",
              "location":{
                "x":162,
                "y":11},
              "size":{
                "width":27,
                "height":39}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"c1e95353ceee453cbdb823b60bdddaa9",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Myriad Bold', 'Myriad'",
                  "fontSize":"16px",
                  "fontWeight":"bold",
                  "location":{
                    "x":162,
                    "y":11},
                  "size":{
                    "width":27,
                    "height":39}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/信息输入/u40.png"}},
{
            "id":"772571cde2a9487eb6dcc076577b1e7c",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontName":"'Myriad Bold', 'Myriad'",
              "fontSize":"16px",
              "fontWeight":"bold",
              "location":{
                "x":197,
                "y":11},
              "size":{
                "width":26,
                "height":39}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"a6e5d12f45b64b26aff5a0d0bcaf72fa",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Myriad Bold', 'Myriad'",
                  "fontSize":"16px",
                  "fontWeight":"bold",
                  "location":{
                    "x":197,
                    "y":11},
                  "size":{
                    "width":26,
                    "height":39}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/信息输入/u30.png"}},
{
            "id":"964018881a314c3b8f1adf0df78571c6",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontName":"'Myriad Bold', 'Myriad'",
              "fontSize":"16px",
              "fontWeight":"bold",
              "location":{
                "x":228,
                "y":11},
              "size":{
                "width":26,
                "height":39}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"01bba97c7e9a4938ac635cadf96da1b3",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Myriad Bold', 'Myriad'",
                  "fontSize":"16px",
                  "fontWeight":"bold",
                  "location":{
                    "x":228,
                    "y":11},
                  "size":{
                    "width":26,
                    "height":39}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/信息输入/u30.png"}},
{
            "id":"59cc6cbefaa04bb2be9249aabbc40110",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontName":"'Myriad Bold', 'Myriad'",
              "fontSize":"16px",
              "fontWeight":"bold",
              "location":{
                "x":19,
                "y":65},
              "size":{
                "width":26,
                "height":39}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"5cb20a24b39c493184691a573b5b6cda",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Myriad Bold', 'Myriad'",
                  "fontSize":"16px",
                  "fontWeight":"bold",
                  "location":{
                    "x":19,
                    "y":65},
                  "size":{
                    "width":26,
                    "height":39}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/信息输入/u30.png"}},
{
            "id":"bbcb0b8968504c3bb48f082403112dab",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontName":"'Myriad Bold', 'Myriad'",
              "fontSize":"16px",
              "fontWeight":"bold",
              "location":{
                "x":51,
                "y":65},
              "size":{
                "width":26,
                "height":39}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"875b190d7500466a88355c7b2dbcbb71",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Myriad Bold', 'Myriad'",
                  "fontSize":"16px",
                  "fontWeight":"bold",
                  "location":{
                    "x":51,
                    "y":65},
                  "size":{
                    "width":26,
                    "height":39}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/信息输入/u30.png"}},
{
            "id":"f4566f24073c4522b54ca1e6161535e4",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontName":"'Myriad Bold', 'Myriad'",
              "fontSize":"16px",
              "fontWeight":"bold",
              "location":{
                "x":83,
                "y":65},
              "size":{
                "width":27,
                "height":39}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"a89ae09b618244e0bc316baf5f4a4dfc",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Myriad Bold', 'Myriad'",
                  "fontSize":"16px",
                  "fontWeight":"bold",
                  "location":{
                    "x":83,
                    "y":65},
                  "size":{
                    "width":27,
                    "height":39}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/信息输入/u40.png"}},
{
            "id":"2ac2e75187254d2aa8dd53707bad1f83",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontName":"'Myriad Bold', 'Myriad'",
              "fontSize":"16px",
              "fontWeight":"bold",
              "location":{
                "x":116,
                "y":65},
              "size":{
                "width":27,
                "height":39}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"9b030756475448afbfde1962d11b85b1",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Myriad Bold', 'Myriad'",
                  "fontSize":"16px",
                  "fontWeight":"bold",
                  "location":{
                    "x":116,
                    "y":65},
                  "size":{
                    "width":27,
                    "height":39}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/信息输入/u40.png"}},
{
            "id":"5980da12bc7943948a8222499d64ce50",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontName":"'Myriad Bold', 'Myriad'",
              "fontSize":"16px",
              "fontWeight":"bold",
              "location":{
                "x":147,
                "y":65},
              "size":{
                "width":27,
                "height":39}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"1389e0f0a4d24e08a955abc1fe638992",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Myriad Bold', 'Myriad'",
                  "fontSize":"16px",
                  "fontWeight":"bold",
                  "location":{
                    "x":147,
                    "y":65},
                  "size":{
                    "width":27,
                    "height":39}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/信息输入/u40.png"}},
{
            "id":"1f519006930741bdae4be1344344ad0f",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontName":"'Myriad Bold', 'Myriad'",
              "fontSize":"16px",
              "fontWeight":"bold",
              "location":{
                "x":179,
                "y":65},
              "size":{
                "width":26,
                "height":39}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"955722d158234c6c8baece76156c4d13",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Myriad Bold', 'Myriad'",
                  "fontSize":"16px",
                  "fontWeight":"bold",
                  "location":{
                    "x":179,
                    "y":65},
                  "size":{
                    "width":26,
                    "height":39}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/信息输入/u30.png"}},
{
            "id":"3d45ce5cab624e4e8f765251cc4abbb7",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontName":"'Myriad Bold', 'Myriad'",
              "fontSize":"16px",
              "fontWeight":"bold",
              "location":{
                "x":211,
                "y":65},
              "size":{
                "width":26,
                "height":39}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"c45118d20757409ebfbdbb4c62d5f09c",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Myriad Bold', 'Myriad'",
                  "fontSize":"16px",
                  "fontWeight":"bold",
                  "location":{
                    "x":211,
                    "y":65},
                  "size":{
                    "width":26,
                    "height":39}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/信息输入/u30.png"}},
{
            "id":"354756cf2f73469a92d61dd327c6f251",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontName":"'Myriad Bold', 'Myriad'",
              "fontSize":"16px",
              "fontWeight":"bold",
              "location":{
                "x":243,
                "y":65},
              "size":{
                "width":26,
                "height":39}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"73710423b89844758c2987daad839982",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Myriad Bold', 'Myriad'",
                  "fontSize":"16px",
                  "fontWeight":"bold",
                  "location":{
                    "x":243,
                    "y":65},
                  "size":{
                    "width":26,
                    "height":39}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/信息输入/u30.png"}},
{
            "id":"040765993c65462294f67d7639e062a4",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontName":"'Myriad Bold', 'Myriad'",
              "fontSize":"16px",
              "fontWeight":"bold",
              "location":{
                "x":275,
                "y":65},
              "size":{
                "width":26,
                "height":39}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"d7ce8c5bcfca41a78f261a43e1ddc454",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Myriad Bold', 'Myriad'",
                  "fontSize":"16px",
                  "fontWeight":"bold",
                  "location":{
                    "x":275,
                    "y":65},
                  "size":{
                    "width":26,
                    "height":39}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/信息输入/u30.png"}},
{
            "id":"714a0952df0146f8ba122c164574fbb6",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontName":"'Myriad Bold', 'Myriad'",
              "fontSize":"16px",
              "fontWeight":"bold",
              "location":{
                "x":51,
                "y":120},
              "size":{
                "width":27,
                "height":39}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"4a417d84249b4703a61e6938dbeb1ae4",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Myriad Bold', 'Myriad'",
                  "fontSize":"16px",
                  "fontWeight":"bold",
                  "location":{
                    "x":51,
                    "y":120},
                  "size":{
                    "width":27,
                    "height":39}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/信息输入/u40.png"}},
{
            "id":"c1e7ff263ea04fb5a8052e97b4115b70",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontName":"'Myriad Bold', 'Myriad'",
              "fontSize":"16px",
              "fontWeight":"bold",
              "location":{
                "x":83,
                "y":120},
              "size":{
                "width":27,
                "height":39}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"10b89a6302214a9f9eef181eee58b409",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Myriad Bold', 'Myriad'",
                  "fontSize":"16px",
                  "fontWeight":"bold",
                  "location":{
                    "x":83,
                    "y":120},
                  "size":{
                    "width":27,
                    "height":39}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/信息输入/u40.png"}},
{
            "id":"952577131c874d37b9e219e6d4aa53dd",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontName":"'Myriad Bold', 'Myriad'",
              "fontSize":"16px",
              "fontWeight":"bold",
              "location":{
                "x":116,
                "y":120},
              "size":{
                "width":27,
                "height":39}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"e658743be4f842eb91de0c56749d7299",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Myriad Bold', 'Myriad'",
                  "fontSize":"16px",
                  "fontWeight":"bold",
                  "location":{
                    "x":116,
                    "y":120},
                  "size":{
                    "width":27,
                    "height":39}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/信息输入/u40.png"}},
{
            "id":"2b9a4cdff00c44bf8312757ac7df60d4",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontName":"'Myriad Bold', 'Myriad'",
              "fontSize":"16px",
              "fontWeight":"bold",
              "location":{
                "x":147,
                "y":120},
              "size":{
                "width":26,
                "height":39}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"cb3fc98dc3864aa38372ec32bfa118e9",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Myriad Bold', 'Myriad'",
                  "fontSize":"16px",
                  "fontWeight":"bold",
                  "location":{
                    "x":147,
                    "y":120},
                  "size":{
                    "width":26,
                    "height":39}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/信息输入/u30.png"}},
{
            "id":"2ea72dd64b754c558ca0e9441526a223",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontName":"'Myriad Bold', 'Myriad'",
              "fontSize":"16px",
              "fontWeight":"bold",
              "location":{
                "x":179,
                "y":120},
              "size":{
                "width":26,
                "height":39}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"701cbd361b5645e386ebc96554b06546",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Myriad Bold', 'Myriad'",
                  "fontSize":"16px",
                  "fontWeight":"bold",
                  "location":{
                    "x":179,
                    "y":120},
                  "size":{
                    "width":26,
                    "height":39}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/信息输入/u30.png"}},
{
            "id":"d497cb3e9c8b411eadcf6646a200ddbe",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontName":"'Myriad Bold', 'Myriad'",
              "fontSize":"16px",
              "fontWeight":"bold",
              "location":{
                "x":211,
                "y":120},
              "size":{
                "width":26,
                "height":39}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"531e719447a6435b847e4174462da128",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Myriad Bold', 'Myriad'",
                  "fontSize":"16px",
                  "fontWeight":"bold",
                  "location":{
                    "x":211,
                    "y":120},
                  "size":{
                    "width":26,
                    "height":39}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/信息输入/u30.png"}},
{
            "id":"edf6b7c8e57042dba6777db9539ebad2",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontName":"'Myriad Bold', 'Myriad'",
              "fontSize":"16px",
              "fontWeight":"bold",
              "location":{
                "x":243,
                "y":120},
              "size":{
                "width":26,
                "height":39}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"b49ba5ad5c1040439a39ade8bf8a7521",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Myriad Bold', 'Myriad'",
                  "fontSize":"16px",
                  "fontWeight":"bold",
                  "location":{
                    "x":243,
                    "y":120},
                  "size":{
                    "width":26,
                    "height":39}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/信息输入/u30.png"}},
{
            "id":"00f5edd51b424bab8515b720f91a8338",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontSize":"16px",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "fill":{
                "fillType":"solid",
                "color":0xFF999999},
              "location":{
                "x":243,
                "y":174},
              "size":{
                "width":73,
                "height":39}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"e57f33cf861745a8b953b936c54f3d40",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"16px",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF999999},
                  "location":{
                    "x":243,
                    "y":174},
                  "size":{
                    "width":73,
                    "height":39}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/信息输入/u82.png"}},
{
            "id":"c91805f9433147a5b5c9df6b7118e6b4",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontSize":"16px",
              "location":{
                "x":83,
                "y":173},
              "size":{
                "width":153,
                "height":39}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"2e2b2a7ad03440a1a0740f1626c05620",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"16px",
                  "location":{
                    "x":83,
                    "y":173},
                  "size":{
                    "width":153,
                    "height":39}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/信息输入/u84.png"}},
{
            "id":"7bd7e5cb18b344a8972204425d380367",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontSize":"16px",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "fill":{
                "fillType":"solid",
                "color":0xFF999999},
              "location":{
                "x":4,
                "y":173},
              "size":{
                "width":73,
                "height":39}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"20c91ae55cbd40d99ac281136a4dd920",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"16px",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF999999},
                  "location":{
                    "x":4,
                    "y":173},
                  "size":{
                    "width":73,
                    "height":39}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/信息输入/u82.png"}},
{
            "id":"4e367dcc85d34316adf38345768b33ed",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontName":"'Myriad Regular', 'Myriad'",
              "fontSize":"16px",
              "fill":{
                "fillType":"solid",
                "color":0xFF999999},
              "location":{
                "x":281,
                "y":120},
              "size":{
                "width":37,
                "height":39}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"8853e1412f3b44869f68d0ef45c6ab61",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Myriad Regular', 'Myriad'",
                  "fontSize":"16px",
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF999999},
                  "location":{
                    "x":281,
                    "y":120},
                  "size":{
                    "width":37,
                    "height":39}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/信息输入/u88.png"}},
{
            "id":"6a1f57cddb654d0988d8e5322391e9d4",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontName":"'Myriad Regular', 'Myriad'",
              "fontSize":"16px",
              "fill":{
                "fillType":"solid",
                "color":0xFF999999},
              "location":{
                "x":4,
                "y":120},
              "size":{
                "width":37,
                "height":39}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"6f9a596597414f6fb99e84fd476e2b39",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Myriad Regular', 'Myriad'",
                  "fontSize":"16px",
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF999999},
                  "location":{
                    "x":4,
                    "y":120},
                  "size":{
                    "width":37,
                    "height":39}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/信息输入/u88.png"}},
{
            "id":"8e2007e376d74da3b32ba5710d5db5fa",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontSize":"16px",
              "location":{
                "x":17,
                "y":137},
              "size":{
                "width":9,
                "height":10},
              "borderWidth":"-1",
              "cornerRadiusTopLeft":"5"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"87b34ca36e604d70a565157d11205bad",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"16px",
                  "location":{
                    "x":17,
                    "y":137},
                  "size":{
                    "width":9,
                    "height":10},
                  "borderWidth":"-1",
                  "cornerRadiusTopLeft":"5"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/信息输入/u92.png"}},
{
            "id":"d5b96e3180784f5ba1da0f68e403d693",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontSize":"16px",
              "location":{
                "x":11,
                "y":130},
              "size":{
                "width":23,
                "height":13},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"b544dd0997244b95a6e9e698397f7459",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"16px",
                  "location":{
                    "x":11,
                    "y":130},
                  "size":{
                    "width":23,
                    "height":13},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/信息输入/u94.png"}},
{
            "id":"ff79e9d2109f45e2b069c457a2ea131f",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontSize":"16px",
              "fill":{
                "fillType":"solid",
                "color":0xFFFCFDFE},
              "location":{
                "x":287,
                "y":130},
              "size":{
                "width":24,
                "height":17},
              "cornerRadiusTopLeft":"7"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"881c2307625049d9bd736b9839b530de",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"16px",
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFFCFDFE},
                  "location":{
                    "x":287,
                    "y":130},
                  "size":{
                    "width":24,
                    "height":17},
                  "cornerRadiusTopLeft":"7"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/信息输入/u96.png"}},
{
            "id":"f37d011e919749faa60c1485f9107530",
            "label":"",
            "type":"horizontalLine",
            "styleType":"horizontalLine",
            "visible":true,
            "style":{
              "location":{
                "x":296,
                "y":136},
              "size":{
                "width":9,
                "height":10},
              "rotation":"315",
              "borderWidth":"4",
              "borderFill":{
                "fillType":"solid",
                "color":0xFF616A79}},
            "adaptiveStyles":{
},
            "images":{
              "start~":"resources/images/transparent.gif",
              "end~":"resources/images/transparent.gif",
              "line~":"images/信息输入/u98_line.png"}},
{
            "id":"d3e9b540a3744c119196901a453f39f9",
            "label":"",
            "type":"horizontalLine",
            "styleType":"horizontalLine",
            "visible":true,
            "style":{
              "location":{
                "x":296,
                "y":135},
              "size":{
                "width":8,
                "height":10},
              "rotation":"225",
              "borderWidth":"4",
              "borderFill":{
                "fillType":"solid",
                "color":0xFF616A79}},
            "adaptiveStyles":{
},
            "images":{
              "start~":"resources/images/transparent.gif",
              "end~":"resources/images/transparent.gif",
              "line~":"images/信息输入/u99_line.png"}}]}}},
  "objectPaths":{
    "bd33c89c1dfd410ba1733d4868c09998":{
      "scriptId":"u0",
      "f1dfbdea093d41b09735aae262127399":{
        "scriptId":"u1"},
      "54ce0076fc284f268413b560877042f3":{
        "scriptId":"u2"},
      "ab9e31cf23e142ee94d04b46c74b970e":{
        "scriptId":"u3"},
      "3ab26a5565ea402f9f26e370e766ab77":{
        "scriptId":"u4"},
      "778d1d4e585c4b1999a8a13f41c86394":{
        "scriptId":"u5"},
      "6393b6169e4944b0a5bacb6e7876f663":{
        "scriptId":"u6"},
      "82466aad239343fd99ca0aa832fce046":{
        "scriptId":"u7"},
      "449f01aeeeb24531a1c8210ccbb014cc":{
        "scriptId":"u8"},
      "3961b32dcc1a40fcbc6bfd22d98eeae2":{
        "scriptId":"u9"},
      "7b559f9ed3de40848129dd2ad0bc1939":{
        "scriptId":"u10"},
      "30ab91e377a6423ab81eff19444f2d2a":{
        "scriptId":"u11"},
      "b41c87afa21f477ea7270b37c48e7eff":{
        "scriptId":"u12"},
      "af1cf1fd332945d298cfea08298ec3ea":{
        "scriptId":"u13"},
      "a2ce34bd582a4f0d973a5b715165689d":{
        "scriptId":"u14"},
      "1b60a919ae904b59919e6507de351e77":{
        "scriptId":"u15"},
      "94059979496c45349791a403f98024ed":{
        "scriptId":"u16"},
      "25da23a08fcb444cbbf1fc72394fd476":{
        "scriptId":"u17"},
      "b78d3bea065748e6888c0f75e83057ed":{
        "scriptId":"u18"},
      "8b2e58b05d324d178a80af84d5a955a9":{
        "scriptId":"u19"},
      "cfe4a760e0c9478db90a300bb7258014":{
        "scriptId":"u20"},
      "598708d1af384602b9a84271fd9fb443":{
        "scriptId":"u21"},
      "bcd9c014b42141d2991ecfeecdfa8069":{
        "scriptId":"u22"}},
    "ed69a02766dd4f38855b8b5cdc0ed426":{
      "scriptId":"u23"},
    "82857c01a865421e98b47bcc19f0ef15":{
      "scriptId":"u24"},
    "91abd424fece45e6b43b62bec14c48dd":{
      "scriptId":"u25"},
    "cefd12d0786a47b2a599dfdb36a75475":{
      "scriptId":"u26"},
    "0ed0134f405b4894ae1bafaf1f94d224":{
      "scriptId":"u27",
      "f6027dd3a01d4ddc8545ac0f83debaad":{
        "scriptId":"u28"},
      "f03764f9f19746bba494e147d06cd5b5":{
        "scriptId":"u29"},
      "414006c5ba3d4647af3e881854e72aba":{
        "scriptId":"u30"},
      "d82e87bdb6884564b7c8bb363db169ed":{
        "scriptId":"u31"},
      "e104c84544484dca9e86c052ec816f1e":{
        "scriptId":"u32"},
      "49873970094b4e27a96700f10c6d99ef":{
        "scriptId":"u33"},
      "cf091cfbd4514a45b33a0e86dac8506b":{
        "scriptId":"u34"},
      "b101d1531c8b4db7afc485150efe0ef8":{
        "scriptId":"u35"},
      "8ed3ca947c5b4bc895ea4e46dd4abe06":{
        "scriptId":"u36"},
      "84e244372d654c7fab63687cf8d4aced":{
        "scriptId":"u37"},
      "348f01660f424b3f8cccc305115aa163":{
        "scriptId":"u38"},
      "667e5d772d2c4116b7b7c9abc5a3f498":{
        "scriptId":"u39"},
      "e342fb61408d4c25ac931fbecd65b229":{
        "scriptId":"u40"},
      "d441b832bb4c422a8b541f79064f5419":{
        "scriptId":"u41"},
      "d7b3afa2886547b7b2628ba9314eac1b":{
        "scriptId":"u42"},
      "ba4669520afc4a2caf201d63d4676a65":{
        "scriptId":"u43"},
      "a1d72e34fb0e4f82bc81a4b77958f5ad":{
        "scriptId":"u44"},
      "c1e95353ceee453cbdb823b60bdddaa9":{
        "scriptId":"u45"},
      "772571cde2a9487eb6dcc076577b1e7c":{
        "scriptId":"u46"},
      "a6e5d12f45b64b26aff5a0d0bcaf72fa":{
        "scriptId":"u47"},
      "964018881a314c3b8f1adf0df78571c6":{
        "scriptId":"u48"},
      "01bba97c7e9a4938ac635cadf96da1b3":{
        "scriptId":"u49"},
      "59cc6cbefaa04bb2be9249aabbc40110":{
        "scriptId":"u50"},
      "5cb20a24b39c493184691a573b5b6cda":{
        "scriptId":"u51"},
      "bbcb0b8968504c3bb48f082403112dab":{
        "scriptId":"u52"},
      "875b190d7500466a88355c7b2dbcbb71":{
        "scriptId":"u53"},
      "f4566f24073c4522b54ca1e6161535e4":{
        "scriptId":"u54"},
      "a89ae09b618244e0bc316baf5f4a4dfc":{
        "scriptId":"u55"},
      "2ac2e75187254d2aa8dd53707bad1f83":{
        "scriptId":"u56"},
      "9b030756475448afbfde1962d11b85b1":{
        "scriptId":"u57"},
      "5980da12bc7943948a8222499d64ce50":{
        "scriptId":"u58"},
      "1389e0f0a4d24e08a955abc1fe638992":{
        "scriptId":"u59"},
      "1f519006930741bdae4be1344344ad0f":{
        "scriptId":"u60"},
      "955722d158234c6c8baece76156c4d13":{
        "scriptId":"u61"},
      "3d45ce5cab624e4e8f765251cc4abbb7":{
        "scriptId":"u62"},
      "c45118d20757409ebfbdbb4c62d5f09c":{
        "scriptId":"u63"},
      "354756cf2f73469a92d61dd327c6f251":{
        "scriptId":"u64"},
      "73710423b89844758c2987daad839982":{
        "scriptId":"u65"},
      "040765993c65462294f67d7639e062a4":{
        "scriptId":"u66"},
      "d7ce8c5bcfca41a78f261a43e1ddc454":{
        "scriptId":"u67"},
      "714a0952df0146f8ba122c164574fbb6":{
        "scriptId":"u68"},
      "4a417d84249b4703a61e6938dbeb1ae4":{
        "scriptId":"u69"},
      "c1e7ff263ea04fb5a8052e97b4115b70":{
        "scriptId":"u70"},
      "10b89a6302214a9f9eef181eee58b409":{
        "scriptId":"u71"},
      "952577131c874d37b9e219e6d4aa53dd":{
        "scriptId":"u72"},
      "e658743be4f842eb91de0c56749d7299":{
        "scriptId":"u73"},
      "2b9a4cdff00c44bf8312757ac7df60d4":{
        "scriptId":"u74"},
      "cb3fc98dc3864aa38372ec32bfa118e9":{
        "scriptId":"u75"},
      "2ea72dd64b754c558ca0e9441526a223":{
        "scriptId":"u76"},
      "701cbd361b5645e386ebc96554b06546":{
        "scriptId":"u77"},
      "d497cb3e9c8b411eadcf6646a200ddbe":{
        "scriptId":"u78"},
      "531e719447a6435b847e4174462da128":{
        "scriptId":"u79"},
      "edf6b7c8e57042dba6777db9539ebad2":{
        "scriptId":"u80"},
      "b49ba5ad5c1040439a39ade8bf8a7521":{
        "scriptId":"u81"},
      "00f5edd51b424bab8515b720f91a8338":{
        "scriptId":"u82"},
      "e57f33cf861745a8b953b936c54f3d40":{
        "scriptId":"u83"},
      "c91805f9433147a5b5c9df6b7118e6b4":{
        "scriptId":"u84"},
      "2e2b2a7ad03440a1a0740f1626c05620":{
        "scriptId":"u85"},
      "7bd7e5cb18b344a8972204425d380367":{
        "scriptId":"u86"},
      "20c91ae55cbd40d99ac281136a4dd920":{
        "scriptId":"u87"},
      "4e367dcc85d34316adf38345768b33ed":{
        "scriptId":"u88"},
      "8853e1412f3b44869f68d0ef45c6ab61":{
        "scriptId":"u89"},
      "6a1f57cddb654d0988d8e5322391e9d4":{
        "scriptId":"u90"},
      "6f9a596597414f6fb99e84fd476e2b39":{
        "scriptId":"u91"},
      "8e2007e376d74da3b32ba5710d5db5fa":{
        "scriptId":"u92"},
      "87b34ca36e604d70a565157d11205bad":{
        "scriptId":"u93"},
      "d5b96e3180784f5ba1da0f68e403d693":{
        "scriptId":"u94"},
      "b544dd0997244b95a6e9e698397f7459":{
        "scriptId":"u95"},
      "ff79e9d2109f45e2b069c457a2ea131f":{
        "scriptId":"u96"},
      "881c2307625049d9bd736b9839b530de":{
        "scriptId":"u97"},
      "f37d011e919749faa60c1485f9107530":{
        "scriptId":"u98"},
      "d3e9b540a3744c119196901a453f39f9":{
        "scriptId":"u99"}},
    "326e5ec0293e44cfbbefa58240ad139a":{
      "scriptId":"u100"},
    "417394d173994b5683778a68e483d2ab":{
      "scriptId":"u101"},
    "a511d65a85284ff89a041700cfb03290":{
      "scriptId":"u102"}}});