$axure.loadCurrentPage({
  "url":"优惠券.html",
  "generationDate":new Date(1438070190230.94),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"4cbcad0c1401457e81d0425f4edf960e",
    "type":"Axure:Page",
    "name":"优惠券",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"171dc2a7fc004266be48393d70f7cf76",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"0b7481d9291846af9389708a818f6ee6"},
{
          "id":"811b8a86f39942659074e7fd8260a480",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":36,
              "y":109},
            "size":{
              "width":320,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"eaa7af95b11941758d73c002f02c3392",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":36,
                  "y":109},
                "size":{
                  "width":320,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注册/u23.png"}},
{
          "id":"27547929afec4f3c8c6aa313f2585305",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":36,
              "y":560}},
          "adaptiveStyles":{
},
          "masterId":"fdbf0fa723dd4210bf40f97a1db88128"},
{
          "id":"c9f883a09f13493386b00d772b4f6dad",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":150,
              "y":116},
            "size":{
              "width":101,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dbbceca853c5435c8c8d44dac48629a1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":150,
                  "y":116},
                "size":{
                  "width":101,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"afd1631f983a496e8b6139a43cf03713",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":48,
              "y":120},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ce766a39f2a64b78937ff8b326e72d97",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":48,
                  "y":120},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"02caec02e77a4be69f40f7cb8e20312b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":320,
              "y":120},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b572353f488149c4aa9a9218fb09f26a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":320,
                  "y":120},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"59e3c93ade884cdca7e36e079fe07906",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":48,
              "y":286}},
          "adaptiveStyles":{
},
          "masterId":"c8245493100d44e99376ad7f91ca4753"},
{
          "id":"874e1fa00f9d4ef1aca23bf1759da1e7",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":48,
              "y":372}},
          "adaptiveStyles":{
},
          "masterId":"c8245493100d44e99376ad7f91ca4753"},
{
          "id":"68366e3d7a7d48fb839f556c24cefea4",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":48,
              "y":458}},
          "adaptiveStyles":{
},
          "masterId":"c8245493100d44e99376ad7f91ca4753"},
{
          "id":"6ae905a926fd4d748f8bbd91ae97d40e",
          "label":"",
          "type":"menuObject",
          "styleType":"menuObject",
          "visible":true,
          "style":{
            "location":{
              "x":36,
              "y":148},
            "size":{
              "width":320,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"09ab9d6089f14f36b1adc9f3311ddd49",
              "label":"",
              "type":"table",
              "styleType":"table",
              "visible":true,
              "style":{
                "size":{
                  "width":320,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"aad8bcb65dcf42579c025bf185a8bf56",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "size":{
                      "width":53,
                      "height":30},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"6f1272294fc5433e8187080d554b7390",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "size":{
                          "width":53,
                          "height":30},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/优惠券/u80.png"}},
{
                  "id":"7906b8fb3ca14fc5809e6cc29ffcbcc4",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":53,
                      "y":0},
                    "size":{
                      "width":53,
                      "height":30},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"31f497117b8542fca25b84ea309bb395",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":53,
                          "y":0},
                        "size":{
                          "width":53,
                          "height":30},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/优惠券/u80.png"}},
{
                  "id":"8e528c64ccce420f826de276b06e6305",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":106,
                      "y":0},
                    "size":{
                      "width":53,
                      "height":30},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"29e79e3034ff435c94c70a87aadeee4d",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":106,
                          "y":0},
                        "size":{
                          "width":53,
                          "height":30},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/优惠券/u80.png"}},
{
                  "id":"f24b480769d442278fe62ffe55fbf9c2",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":265,
                      "y":0},
                    "size":{
                      "width":55,
                      "height":30},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"67cbc5d715a340c69ae740bbe585cc85",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":265,
                          "y":0},
                        "size":{
                          "width":55,
                          "height":30},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/优惠券/u90.png"}},
{
                  "id":"4ffba7fcfd5045c9b99ec267414f1168",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":212,
                      "y":0},
                    "size":{
                      "width":53,
                      "height":30},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"cc45c374f4bf4858a8c289438b666cf0",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":212,
                          "y":0},
                        "size":{
                          "width":53,
                          "height":30},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/优惠券/u80.png"}},
{
                  "id":"2349bdf282dd4516bde8d0ce8e2c79ec",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":159,
                      "y":0},
                    "size":{
                      "width":53,
                      "height":30},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"97b50c6c8887489d8ecac14b47012571",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":159,
                          "y":0},
                        "size":{
                          "width":53,
                          "height":30},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/优惠券/u80.png"}}]}]},
{
          "id":"91e1d361cb6b436bad8798537aed7fe5",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":48,
              "y":200}},
          "adaptiveStyles":{
},
          "masterId":"c8245493100d44e99376ad7f91ca4753"}]}},
  "masters":{
    "0b7481d9291846af9389708a818f6ee6":{
      "packageId":"0b7481d9291846af9389708a818f6ee6",
      "type":"Axure:Master",
      "name":"手机",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"f1dfbdea093d41b09735aae262127399",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "size":{
                "width":388,
                "height":720},
              "borderWidth":"3",
              "borderFill":{
                "fillType":"solid",
                "color":0xFFCCCCCC},
              "cornerRadiusTopLeft":"23"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"54ce0076fc284f268413b560877042f3",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":388,
                    "height":720},
                  "borderWidth":"3",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFCCCCCC},
                  "cornerRadiusTopLeft":"23"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/登录/u1.png"}},
{
            "id":"ab9e31cf23e142ee94d04b46c74b970e",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFFF2F2F2},
              "location":{
                "x":36,
                "y":91},
              "size":{
                "width":320,
                "height":480},
              "borderWidth":"-1",
              "borderFill":{
                "fillType":"solid",
                "color":0xFFFFFF}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"3ab26a5565ea402f9f26e370e766ab77",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFF2F2F2},
                  "location":{
                    "x":36,
                    "y":91},
                  "size":{
                    "width":320,
                    "height":480},
                  "borderWidth":"-1",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFFFFF}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/登录/u3.png"}},
{
            "id":"778d1d4e585c4b1999a8a13f41c86394",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFF333333},
              "location":{
                "x":36,
                "y":91},
              "size":{
                "width":320,
                "height":20},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFFFFF}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"6393b6169e4944b0a5bacb6e7876f663",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF333333},
                  "location":{
                    "x":36,
                    "y":91},
                  "size":{
                    "width":320,
                    "height":20},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFFFFF}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/登录/u5.png"}},
{
            "id":"82466aad239343fd99ca0aa832fce046",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFFF2F2F2},
              "location":{
                "x":159,
                "y":610},
              "size":{
                "width":60,
                "height":61},
              "borderWidth":"3",
              "borderFill":{
                "fillType":"solid",
                "color":0xFFCCCCCC},
              "cornerRadiusTopLeft":"100"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"449f01aeeeb24531a1c8210ccbb014cc",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFF2F2F2},
                  "location":{
                    "x":159,
                    "y":610},
                  "size":{
                    "width":60,
                    "height":61},
                  "borderWidth":"3",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFCCCCCC},
                  "cornerRadiusTopLeft":"100"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/登录/u7.png"}},
{
            "id":"3961b32dcc1a40fcbc6bfd22d98eeae2",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFF999999},
              "location":{
                "x":179,
                "y":631},
              "size":{
                "width":20,
                "height":20},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFFFFF},
              "cornerRadiusTopLeft":"4"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"7b559f9ed3de40848129dd2ad0bc1939",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF999999},
                  "location":{
                    "x":179,
                    "y":631},
                  "size":{
                    "width":20,
                    "height":20},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFFFFF},
                  "cornerRadiusTopLeft":"4"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/登录/u9.png"}},
{
            "id":"30ab91e377a6423ab81eff19444f2d2a",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"12px",
              "horizontalAlignment":"center",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "location":{
                "x":164,
                "y":94},
              "size":{
                "width":75,
                "height":15},
              "rotation":"0",
              "textRotation":"0"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"b41c87afa21f477ea7270b37c48e7eff",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"12px",
                  "horizontalAlignment":"center",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "location":{
                    "x":164,
                    "y":94},
                  "size":{
                    "width":75,
                    "height":15},
                  "rotation":"0",
                  "textRotation":"0"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"af1cf1fd332945d298cfea08298ec3ea",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":323,
                "y":95},
              "size":{
                "width":22,
                "height":11},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFFFFF}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"a2ce34bd582a4f0d973a5b715165689d",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":323,
                    "y":95},
                  "size":{
                    "width":22,
                    "height":11},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFFFFF}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/登录/u13.png"}},
{
            "id":"1b60a919ae904b59919e6507de351e77",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":345,
                "y":98},
              "size":{
                "width":4,
                "height":5},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFFFFF},
              "cornerRadiusTopLeft":"1"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"94059979496c45349791a403f98024ed",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":345,
                    "y":98},
                  "size":{
                    "width":4,
                    "height":5},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFFFFF},
                  "cornerRadiusTopLeft":"1"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/登录/u15.png"}},
{
            "id":"25da23a08fcb444cbbf1fc72394fd476",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"11px",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "location":{
                "x":43,
                "y":94},
              "size":{
                "width":82,
                "height":14},
              "rotation":"0",
              "textRotation":"0"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"b78d3bea065748e6888c0f75e83057ed",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"11px",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "location":{
                    "x":43,
                    "y":94},
                  "size":{
                    "width":82,
                    "height":14},
                  "rotation":"0",
                  "textRotation":"0"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"8b2e58b05d324d178a80af84d5a955a9",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFF999999},
              "location":{
                "x":174,
                "y":64},
              "size":{
                "width":50,
                "height":8},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFFFFF},
              "cornerRadiusTopLeft":"6"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"cfe4a760e0c9478db90a300bb7258014",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF999999},
                  "location":{
                    "x":174,
                    "y":64},
                  "size":{
                    "width":50,
                    "height":8},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFFFFF},
                  "cornerRadiusTopLeft":"6"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/登录/u19.png"}},
{
            "id":"598708d1af384602b9a84271fd9fb443",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFF999999},
              "location":{
                "x":195,
                "y":50},
              "size":{
                "width":10,
                "height":10},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFFFFF},
              "cornerRadiusTopLeft":"8"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"bcd9c014b42141d2991ecfeecdfa8069",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF999999},
                  "location":{
                    "x":195,
                    "y":50},
                  "size":{
                    "width":10,
                    "height":10},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFFFFF},
                  "cornerRadiusTopLeft":"8"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/登录/u21.png"}}]}},
    "fdbf0fa723dd4210bf40f97a1db88128":{
      "packageId":"fdbf0fa723dd4210bf40f97a1db88128",
      "type":"Axure:Master",
      "name":"新母版 3",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"f04e46641eb84435bb35e3e03b9acc2d",
            "label":"",
            "type":"menuObject",
            "styleType":"menuObject",
            "visible":true,
            "style":{
              "size":{
                "width":320,
                "height":50}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"e56d860593fb4430b55663ef0bcabf6b",
                "label":"",
                "type":"table",
                "styleType":"table",
                "visible":true,
                "style":{
                  "size":{
                    "width":320,
                    "height":50}},
                "adaptiveStyles":{
},
                "objects":[{
                    "id":"2c2e98c2e7f048d682c1dc35b032b81f",
                    "label":"商圈",
                    "type":"tableCell",
                    "styleType":"tableCell",
                    "visible":true,
                    "style":{
                      "fontName":"'Arial Negreta', 'Arial'",
                      "fontSize":"14px",
                      "fontWeight":"700",
                      "horizontalAlignment":"center",
                      "verticalAlignment":"middle",
                      "stateStyles":{
                        "mouseOver":{
                          "fill":{
                            "fillType":"solid",
                            "color":0xFFE4E4E4}},
                        "selected":{
                          "foreGroundFill":{
                            "fillType":"solid",
                            "color":0xFFFFFFFF,
                            "opacity":1},
                          "fill":{
                            "fillType":"solid",
                            "color":0xFF333333}}},
                      "size":{
                        "width":80,
                        "height":50},
                      "borderFill":{
                        "fillType":"solid",
                        "color":0xFFCCCCCC}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"c27e9967de0e4a559e8a6123d42973c5",
                        "label":"",
                        "isContained":true,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontName":"'Arial Negreta', 'Arial'",
                          "fontSize":"14px",
                          "fontWeight":"700",
                          "horizontalAlignment":"center",
                          "verticalAlignment":"middle",
                          "stateStyles":{
                            "mouseOver":{
                              "fill":{
                                "fillType":"solid",
                                "color":0xFFE4E4E4}},
                            "selected":{
                              "foreGroundFill":{
                                "fillType":"solid",
                                "color":0xFFFFFFFF,
                                "opacity":1},
                              "fill":{
                                "fillType":"solid",
                                "color":0xFF333333}}},
                          "size":{
                            "width":80,
                            "height":50},
                          "borderFill":{
                            "fillType":"solid",
                            "color":0xFFCCCCCC}},
                        "adaptiveStyles":{
}}],
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"用例 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"在 当前窗口 打开 优惠券",
                                "target":{
                                  "targetType":"page",
                                  "url":"优惠券.html",
                                  "includeVariables":true},
                                "linkType":"current"}]}]}},
                    "tabbable":true,
                    "images":{
                      "normal~":"images/优惠券/商圈_u28.png",
                      "selected~":"images/优惠券/商圈_u28_selected.png",
                      "mouseOver~":"images/优惠券/商圈_u28_mouseOver.png"}},
{
                    "id":"938e17154fbf410aad672ad1edada5b4",
                    "label":"活动",
                    "type":"tableCell",
                    "styleType":"tableCell",
                    "visible":true,
                    "style":{
                      "fontName":"'Arial Negreta', 'Arial'",
                      "fontSize":"14px",
                      "fontWeight":"700",
                      "horizontalAlignment":"center",
                      "verticalAlignment":"middle",
                      "stateStyles":{
                        "mouseOver":{
                          "fill":{
                            "fillType":"solid",
                            "color":0xFFE4E4E4}},
                        "selected":{
                          "foreGroundFill":{
                            "fillType":"solid",
                            "color":0xFFFFFFFF,
                            "opacity":1},
                          "fill":{
                            "fillType":"solid",
                            "color":0xFF333333}}},
                      "fill":{
                        "fillType":"solid",
                        "color":0xFFFFFF},
                      "location":{
                        "x":160,
                        "y":0},
                      "size":{
                        "width":80,
                        "height":50},
                      "borderFill":{
                        "fillType":"solid",
                        "color":0xFFCCCCCC}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"6ab6720582194ad297290f9aacbb77c8",
                        "label":"",
                        "isContained":true,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontName":"'Arial Negreta', 'Arial'",
                          "fontSize":"14px",
                          "fontWeight":"700",
                          "horizontalAlignment":"center",
                          "verticalAlignment":"middle",
                          "stateStyles":{
                            "mouseOver":{
                              "fill":{
                                "fillType":"solid",
                                "color":0xFFE4E4E4}},
                            "selected":{
                              "foreGroundFill":{
                                "fillType":"solid",
                                "color":0xFFFFFFFF,
                                "opacity":1},
                              "fill":{
                                "fillType":"solid",
                                "color":0xFF333333}}},
                          "fill":{
                            "fillType":"solid",
                            "color":0xFFFFFF},
                          "location":{
                            "x":160,
                            "y":0},
                          "size":{
                            "width":80,
                            "height":50},
                          "borderFill":{
                            "fillType":"solid",
                            "color":0xFFCCCCCC}},
                        "adaptiveStyles":{
}}],
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"用例 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"在 当前窗口 打开 链接",
                                "target":{
                                  "targetType":"page",
                                  "includeVariables":true},
                                "linkType":"current"}]}]}},
                    "tabbable":true,
                    "images":{
                      "normal~":"images/优惠券/抽奖_u30.png",
                      "selected~":"images/优惠券/商圈_u28_selected.png",
                      "mouseOver~":"images/优惠券/商圈_u28_mouseOver.png"}},
{
                    "id":"13939581c1e1494fbf2606e44be268b4",
                    "label":"我",
                    "type":"tableCell",
                    "styleType":"tableCell",
                    "visible":true,
                    "style":{
                      "fontName":"'Arial Negreta', 'Arial'",
                      "fontSize":"14px",
                      "fontWeight":"700",
                      "horizontalAlignment":"center",
                      "verticalAlignment":"middle",
                      "stateStyles":{
                        "mouseOver":{
                          "fill":{
                            "fillType":"solid",
                            "color":0xFFE4E4E4}},
                        "selected":{
                          "foreGroundFill":{
                            "fillType":"solid",
                            "color":0xFFFFFFFF,
                            "opacity":1},
                          "fill":{
                            "fillType":"solid",
                            "color":0xFF333333}}},
                      "fill":{
                        "fillType":"solid",
                        "color":0xFFFFFF},
                      "location":{
                        "x":240,
                        "y":0},
                      "size":{
                        "width":80,
                        "height":50},
                      "borderFill":{
                        "fillType":"solid",
                        "color":0xFFCCCCCC}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"c28454dab52b41a58a0c9cb4c3039e2a",
                        "label":"",
                        "isContained":true,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontName":"'Arial Negreta', 'Arial'",
                          "fontSize":"14px",
                          "fontWeight":"700",
                          "horizontalAlignment":"center",
                          "verticalAlignment":"middle",
                          "stateStyles":{
                            "mouseOver":{
                              "fill":{
                                "fillType":"solid",
                                "color":0xFFE4E4E4}},
                            "selected":{
                              "foreGroundFill":{
                                "fillType":"solid",
                                "color":0xFFFFFFFF,
                                "opacity":1},
                              "fill":{
                                "fillType":"solid",
                                "color":0xFF333333}}},
                          "fill":{
                            "fillType":"solid",
                            "color":0xFFFFFF},
                          "location":{
                            "x":240,
                            "y":0},
                          "size":{
                            "width":80,
                            "height":50},
                          "borderFill":{
                            "fillType":"solid",
                            "color":0xFFCCCCCC}},
                        "adaptiveStyles":{
}}],
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"用例 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"在 当前窗口 打开 我",
                                "target":{
                                  "targetType":"page",
                                  "url":"我.html",
                                  "includeVariables":true},
                                "linkType":"current"}]}]}},
                    "tabbable":true,
                    "images":{
                      "normal~":"images/优惠券/我_u34.png",
                      "selected~":"images/优惠券/我_u34_selected.png",
                      "mouseOver~":"images/优惠券/我_u34_mouseOver.png"}},
{
                    "id":"9ce6a9bbecce41ef95d8e8846eb6a0a1",
                    "label":"抽奖",
                    "type":"tableCell",
                    "styleType":"tableCell",
                    "visible":true,
                    "style":{
                      "fontName":"'Arial Negreta', 'Arial'",
                      "fontSize":"14px",
                      "fontWeight":"700",
                      "horizontalAlignment":"center",
                      "verticalAlignment":"middle",
                      "stateStyles":{
                        "mouseOver":{
                          "fill":{
                            "fillType":"solid",
                            "color":0xFFE4E4E4}},
                        "selected":{
                          "foreGroundFill":{
                            "fillType":"solid",
                            "color":0xFFFFFFFF,
                            "opacity":1},
                          "fill":{
                            "fillType":"solid",
                            "color":0xFF333333}}},
                      "fill":{
                        "fillType":"solid",
                        "color":0xFFFFFF},
                      "location":{
                        "x":80,
                        "y":0},
                      "size":{
                        "width":80,
                        "height":50},
                      "borderFill":{
                        "fillType":"solid",
                        "color":0xFFCCCCCC}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"0fd61227d96a45829fb37ca41b572377",
                        "label":"",
                        "isContained":true,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontName":"'Arial Negreta', 'Arial'",
                          "fontSize":"14px",
                          "fontWeight":"700",
                          "horizontalAlignment":"center",
                          "verticalAlignment":"middle",
                          "stateStyles":{
                            "mouseOver":{
                              "fill":{
                                "fillType":"solid",
                                "color":0xFFE4E4E4}},
                            "selected":{
                              "foreGroundFill":{
                                "fillType":"solid",
                                "color":0xFFFFFFFF,
                                "opacity":1},
                              "fill":{
                                "fillType":"solid",
                                "color":0xFF333333}}},
                          "fill":{
                            "fillType":"solid",
                            "color":0xFFFFFF},
                          "location":{
                            "x":80,
                            "y":0},
                          "size":{
                            "width":80,
                            "height":50},
                          "borderFill":{
                            "fillType":"solid",
                            "color":0xFFCCCCCC}},
                        "adaptiveStyles":{
}}],
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"用例 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"在 当前窗口 打开 活动",
                                "target":{
                                  "targetType":"page",
                                  "url":"活动.html",
                                  "includeVariables":true},
                                "linkType":"current"}]}]}},
                    "tabbable":true,
                    "images":{
                      "normal~":"images/优惠券/抽奖_u30.png",
                      "selected~":"images/优惠券/商圈_u28_selected.png",
                      "mouseOver~":"images/优惠券/商圈_u28_mouseOver.png"}}]}]}]}},
    "c8245493100d44e99376ad7f91ca4753":{
      "packageId":"c8245493100d44e99376ad7f91ca4753",
      "type":"Axure:Master",
      "name":"优惠券",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"31e7a5be681b4c42b223eb980a3010e0",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "size":{
                "width":300,
                "height":76},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFCCCCCC},
              "cornerRadiusTopLeft":"10"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"48547093c9a7475fb3867c0e756a085a",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":300,
                    "height":76},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFCCCCCC},
                  "cornerRadiusTopLeft":"10"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/优惠券/u43.png",
              "normal~":"images/优惠券/u43.png",
              "normal~":"images/优惠券/u43.png",
              "normal~":"images/优惠券/u43.png"}},
{
            "id":"3fbd12537bb14130b8aa4088b434ea18",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"14px",
              "location":{
                "x":75,
                "y":43},
              "size":{
                "width":127,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"3126b035ec954780933e2994a8a52254",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"14px",
                  "location":{
                    "x":75,
                    "y":43},
                  "size":{
                    "width":127,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif",
              "normal~":"resources/images/transparent.gif",
              "normal~":"resources/images/transparent.gif",
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"a5def953d3ac4d67b6a5e9d9ec4f7759",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":12,
                "y":17},
              "size":{
                "width":50,
                "height":44},
              "borderWidth":"1",
              "borderFill":{
                "fillType":"solid",
                "color":0xFFF2F2F2},
              "cornerRadiusTopLeft":"71"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"b41609890af64f14966025a6f3365f3e",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":12,
                    "y":17},
                  "size":{
                    "width":50,
                    "height":44},
                  "borderWidth":"1",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFF2F2F2},
                  "cornerRadiusTopLeft":"71"},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 优惠券详情",
                        "target":{
                          "targetType":"page",
                          "url":"优惠券详情.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/优惠券/u47.png",
              "normal~":"images/优惠券/u47.png",
              "normal~":"images/优惠券/u47.png",
              "normal~":"images/优惠券/u47.png"}},
{
            "id":"bd0354890528471486eea2ea06735031",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'Arial Negreta', 'Arial'",
              "fontSize":"18px",
              "fontWeight":"700",
              "location":{
                "x":75,
                "y":17},
              "size":{
                "width":83,
                "height":22}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"c59118f9ddbd44eb9a16b2256d3802a9",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial Negreta', 'Arial'",
                  "fontSize":"18px",
                  "fontWeight":"700",
                  "location":{
                    "x":75,
                    "y":17},
                  "size":{
                    "width":83,
                    "height":22}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 优惠券详情",
                        "target":{
                          "targetType":"page",
                          "url":"优惠券详情.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif",
              "normal~":"resources/images/transparent.gif",
              "normal~":"resources/images/transparent.gif",
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"fb6b7d42a57c4de5ad2170e4e22ec3e3",
            "label":"",
            "type":"buttonShape",
            "styleType":"h2",
            "visible":true,
            "style":{
              "fontSize":"16px",
              "location":{
                "x":241,
                "y":27},
              "size":{
                "width":33,
                "height":19}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"7fe34daff82e47f9b1bdcd993df9b51c",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"16px",
                  "location":{
                    "x":241,
                    "y":27},
                  "size":{
                    "width":33,
                    "height":19}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 登录",
                        "target":{
                          "targetType":"page",
                          "url":"登录.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif",
              "normal~":"resources/images/transparent.gif",
              "normal~":"resources/images/transparent.gif",
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"8299cd84b89840e8a9a5f72be6de98f7",
            "label":"",
            "type":"verticalLine",
            "styleType":"verticalLine",
            "visible":true,
            "style":{
              "location":{
                "x":213,
                "y":14},
              "size":{
                "width":10,
                "height":50},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFCCCCCC}},
            "adaptiveStyles":{
},
            "images":{
              "start~":"resources/images/transparent.gif",
              "end~":"resources/images/transparent.gif",
              "line~":"images/优惠券/u53_line.png",
              "start~":"resources/images/transparent.gif",
              "end~":"resources/images/transparent.gif",
              "line~":"images/优惠券/u53_line.png",
              "start~":"resources/images/transparent.gif",
              "end~":"resources/images/transparent.gif",
              "line~":"images/优惠券/u53_line.png",
              "start~":"resources/images/transparent.gif",
              "end~":"resources/images/transparent.gif",
              "line~":"images/优惠券/u53_line.png"}}]}}},
  "objectPaths":{
    "171dc2a7fc004266be48393d70f7cf76":{
      "scriptId":"u0",
      "f1dfbdea093d41b09735aae262127399":{
        "scriptId":"u1"},
      "54ce0076fc284f268413b560877042f3":{
        "scriptId":"u2"},
      "ab9e31cf23e142ee94d04b46c74b970e":{
        "scriptId":"u3"},
      "3ab26a5565ea402f9f26e370e766ab77":{
        "scriptId":"u4"},
      "778d1d4e585c4b1999a8a13f41c86394":{
        "scriptId":"u5"},
      "6393b6169e4944b0a5bacb6e7876f663":{
        "scriptId":"u6"},
      "82466aad239343fd99ca0aa832fce046":{
        "scriptId":"u7"},
      "449f01aeeeb24531a1c8210ccbb014cc":{
        "scriptId":"u8"},
      "3961b32dcc1a40fcbc6bfd22d98eeae2":{
        "scriptId":"u9"},
      "7b559f9ed3de40848129dd2ad0bc1939":{
        "scriptId":"u10"},
      "30ab91e377a6423ab81eff19444f2d2a":{
        "scriptId":"u11"},
      "b41c87afa21f477ea7270b37c48e7eff":{
        "scriptId":"u12"},
      "af1cf1fd332945d298cfea08298ec3ea":{
        "scriptId":"u13"},
      "a2ce34bd582a4f0d973a5b715165689d":{
        "scriptId":"u14"},
      "1b60a919ae904b59919e6507de351e77":{
        "scriptId":"u15"},
      "94059979496c45349791a403f98024ed":{
        "scriptId":"u16"},
      "25da23a08fcb444cbbf1fc72394fd476":{
        "scriptId":"u17"},
      "b78d3bea065748e6888c0f75e83057ed":{
        "scriptId":"u18"},
      "8b2e58b05d324d178a80af84d5a955a9":{
        "scriptId":"u19"},
      "cfe4a760e0c9478db90a300bb7258014":{
        "scriptId":"u20"},
      "598708d1af384602b9a84271fd9fb443":{
        "scriptId":"u21"},
      "bcd9c014b42141d2991ecfeecdfa8069":{
        "scriptId":"u22"}},
    "811b8a86f39942659074e7fd8260a480":{
      "scriptId":"u23"},
    "eaa7af95b11941758d73c002f02c3392":{
      "scriptId":"u24"},
    "27547929afec4f3c8c6aa313f2585305":{
      "scriptId":"u25",
      "f04e46641eb84435bb35e3e03b9acc2d":{
        "scriptId":"u26"},
      "e56d860593fb4430b55663ef0bcabf6b":{
        "scriptId":"u27"},
      "2c2e98c2e7f048d682c1dc35b032b81f":{
        "scriptId":"u28"},
      "c27e9967de0e4a559e8a6123d42973c5":{
        "scriptId":"u29"},
      "9ce6a9bbecce41ef95d8e8846eb6a0a1":{
        "scriptId":"u30"},
      "0fd61227d96a45829fb37ca41b572377":{
        "scriptId":"u31"},
      "938e17154fbf410aad672ad1edada5b4":{
        "scriptId":"u32"},
      "6ab6720582194ad297290f9aacbb77c8":{
        "scriptId":"u33"},
      "13939581c1e1494fbf2606e44be268b4":{
        "scriptId":"u34"},
      "c28454dab52b41a58a0c9cb4c3039e2a":{
        "scriptId":"u35"}},
    "c9f883a09f13493386b00d772b4f6dad":{
      "scriptId":"u36"},
    "dbbceca853c5435c8c8d44dac48629a1":{
      "scriptId":"u37"},
    "afd1631f983a496e8b6139a43cf03713":{
      "scriptId":"u38"},
    "ce766a39f2a64b78937ff8b326e72d97":{
      "scriptId":"u39"},
    "02caec02e77a4be69f40f7cb8e20312b":{
      "scriptId":"u40"},
    "b572353f488149c4aa9a9218fb09f26a":{
      "scriptId":"u41"},
    "59e3c93ade884cdca7e36e079fe07906":{
      "scriptId":"u42",
      "31e7a5be681b4c42b223eb980a3010e0":{
        "scriptId":"u43"},
      "48547093c9a7475fb3867c0e756a085a":{
        "scriptId":"u44"},
      "3fbd12537bb14130b8aa4088b434ea18":{
        "scriptId":"u45"},
      "3126b035ec954780933e2994a8a52254":{
        "scriptId":"u46"},
      "a5def953d3ac4d67b6a5e9d9ec4f7759":{
        "scriptId":"u47"},
      "b41609890af64f14966025a6f3365f3e":{
        "scriptId":"u48"},
      "bd0354890528471486eea2ea06735031":{
        "scriptId":"u49"},
      "c59118f9ddbd44eb9a16b2256d3802a9":{
        "scriptId":"u50"},
      "fb6b7d42a57c4de5ad2170e4e22ec3e3":{
        "scriptId":"u51"},
      "7fe34daff82e47f9b1bdcd993df9b51c":{
        "scriptId":"u52"},
      "8299cd84b89840e8a9a5f72be6de98f7":{
        "scriptId":"u53"}},
    "874e1fa00f9d4ef1aca23bf1759da1e7":{
      "scriptId":"u54",
      "31e7a5be681b4c42b223eb980a3010e0":{
        "scriptId":"u55"},
      "48547093c9a7475fb3867c0e756a085a":{
        "scriptId":"u56"},
      "3fbd12537bb14130b8aa4088b434ea18":{
        "scriptId":"u57"},
      "3126b035ec954780933e2994a8a52254":{
        "scriptId":"u58"},
      "a5def953d3ac4d67b6a5e9d9ec4f7759":{
        "scriptId":"u59"},
      "b41609890af64f14966025a6f3365f3e":{
        "scriptId":"u60"},
      "bd0354890528471486eea2ea06735031":{
        "scriptId":"u61"},
      "c59118f9ddbd44eb9a16b2256d3802a9":{
        "scriptId":"u62"},
      "fb6b7d42a57c4de5ad2170e4e22ec3e3":{
        "scriptId":"u63"},
      "7fe34daff82e47f9b1bdcd993df9b51c":{
        "scriptId":"u64"},
      "8299cd84b89840e8a9a5f72be6de98f7":{
        "scriptId":"u65"}},
    "68366e3d7a7d48fb839f556c24cefea4":{
      "scriptId":"u66",
      "31e7a5be681b4c42b223eb980a3010e0":{
        "scriptId":"u67"},
      "48547093c9a7475fb3867c0e756a085a":{
        "scriptId":"u68"},
      "3fbd12537bb14130b8aa4088b434ea18":{
        "scriptId":"u69"},
      "3126b035ec954780933e2994a8a52254":{
        "scriptId":"u70"},
      "a5def953d3ac4d67b6a5e9d9ec4f7759":{
        "scriptId":"u71"},
      "b41609890af64f14966025a6f3365f3e":{
        "scriptId":"u72"},
      "bd0354890528471486eea2ea06735031":{
        "scriptId":"u73"},
      "c59118f9ddbd44eb9a16b2256d3802a9":{
        "scriptId":"u74"},
      "fb6b7d42a57c4de5ad2170e4e22ec3e3":{
        "scriptId":"u75"},
      "7fe34daff82e47f9b1bdcd993df9b51c":{
        "scriptId":"u76"},
      "8299cd84b89840e8a9a5f72be6de98f7":{
        "scriptId":"u77"}},
    "6ae905a926fd4d748f8bbd91ae97d40e":{
      "scriptId":"u78"},
    "09ab9d6089f14f36b1adc9f3311ddd49":{
      "scriptId":"u79"},
    "aad8bcb65dcf42579c025bf185a8bf56":{
      "scriptId":"u80"},
    "6f1272294fc5433e8187080d554b7390":{
      "scriptId":"u81"},
    "7906b8fb3ca14fc5809e6cc29ffcbcc4":{
      "scriptId":"u82"},
    "31f497117b8542fca25b84ea309bb395":{
      "scriptId":"u83"},
    "8e528c64ccce420f826de276b06e6305":{
      "scriptId":"u84"},
    "29e79e3034ff435c94c70a87aadeee4d":{
      "scriptId":"u85"},
    "2349bdf282dd4516bde8d0ce8e2c79ec":{
      "scriptId":"u86"},
    "97b50c6c8887489d8ecac14b47012571":{
      "scriptId":"u87"},
    "4ffba7fcfd5045c9b99ec267414f1168":{
      "scriptId":"u88"},
    "cc45c374f4bf4858a8c289438b666cf0":{
      "scriptId":"u89"},
    "f24b480769d442278fe62ffe55fbf9c2":{
      "scriptId":"u90"},
    "67cbc5d715a340c69ae740bbe585cc85":{
      "scriptId":"u91"},
    "91e1d361cb6b436bad8798537aed7fe5":{
      "scriptId":"u92",
      "31e7a5be681b4c42b223eb980a3010e0":{
        "scriptId":"u93"},
      "48547093c9a7475fb3867c0e756a085a":{
        "scriptId":"u94"},
      "3fbd12537bb14130b8aa4088b434ea18":{
        "scriptId":"u95"},
      "3126b035ec954780933e2994a8a52254":{
        "scriptId":"u96"},
      "a5def953d3ac4d67b6a5e9d9ec4f7759":{
        "scriptId":"u97"},
      "b41609890af64f14966025a6f3365f3e":{
        "scriptId":"u98"},
      "bd0354890528471486eea2ea06735031":{
        "scriptId":"u99"},
      "c59118f9ddbd44eb9a16b2256d3802a9":{
        "scriptId":"u100"},
      "fb6b7d42a57c4de5ad2170e4e22ec3e3":{
        "scriptId":"u101"},
      "7fe34daff82e47f9b1bdcd993df9b51c":{
        "scriptId":"u102"},
      "8299cd84b89840e8a9a5f72be6de98f7":{
        "scriptId":"u103"}}}});